projectcalico/calicoctl

docs/Orchestrators.md
Remove incorrect reference to split-brain in etcd setup guide.
=> Update etcd instructions in Orchestrators.md

docs/GettingStarted.md
Update docs to refer to the new 0.0.7 release.
=> Docs for v0.0.7

calicoctl.py
Incorrect comment in group_remove_container
=> Fix comment typo

README.md, build_calicoctl/requirements.txt, calicoctl.py, docs/GettingStarted.md, node/adapter/datastore.py, node/adapter/powerstrip-calico.py, tests/add_container.sh, tests/mainline.sh, tests/unit/datastore_test.py
Add & remove tags
Update profile rules
=> Profile Commands

node/adapter/powerstrip-calico.py
Fix an issue where Powerstrip-calico always sets net=None for containers.  Instead, only do this if CALICO_IP is defined in the environment variables.
This allows non-Calico networked containers, for example, if you need to start a container with host networking.
=> Allow non calico powerstrip

calicoctl.py, node/adapter/docker_restart.py, tests/unix_socket.sh
Tested on Centos 7.0 only (so far)
=> Get unix socket stuff working on redhat

calicoctl.py
=> Truncate workload IDs

calicoctl.py, node/adapter/datastore.py, tests/unit/datastore_test.py
This pull request addresses enhancement issue #70.
I've added host, workload type and workload ID to the table.
=> Add more detail to the show profile command

calicoctl.py, node/adapter/datastore.py, run_fvs.sh, tests/fv/add_container.sh, tests/fv/add_ip.sh, tests/fv/arg_parsing.sh, tests/fv/mainline.sh, tests/fv/no_powerstrip.sh, tests/fv/unix_socket.sh, tests/unit/datastore_test.py
This pull request is a fix for issue #96 
See issue for details of fix.
=> Issue 96: Improve error msgs for calicoctl command failures

Dockerfile, build_calicoctl/Dockerfile
I've not tested this yet, so please only review it if the tests pass!
The only bit I'm worried about is removing  python-zmq (which should be fine).
=> Misc Dockerfile cleanups

build_calicoctl/requirements.txt, node/adapter/netns.py, node/adapter/requirements.txt
Undo changes to add nsenter until we determine a different approach for library loading.
=> Do not import nsenter as it causes seg fault with certain varions of libc

docs/ManualClusterSetup.md, docs/Orchestrators.md
=> Update docs to give options for using latest beta or specific version

calico_containers/adapter/datastore.py, calico_containers/tests/unit/datastore_test.py
=> Ensure Rules objects can be converted to JSON

calico_containers/docker_plugin.py, calico_containers/pycalico/requirements.txt
Makes the plugin a little more robust.
=> Add timeout for "ip" subprocess calls

calico_containers/docker_plugin.py
Simple fix to make flask a little more friendly to libnetwork.
=> Libnetwork sane errors

calico_containers/calicoctl.py
=> Sort tables.

calico_containers/tests/st/docker_host.py, calico_containers/tests/st/test_add_container.py, calico_containers/tests/st/test_add_ip.py, calico_containers/tests/st/test_arg_parsing.py, calico_containers/tests/st/test_duplicate_ips.py, calico_containers/tests/st/test_ipv6.py, calico_containers/tests/st/test_multi_host.py, calico_containers/tests/st/test_no_net_driver.py, calico_containers/tests/st/test_profile_commands.py, calico_containers/tests/st/utils.py
Also, various refactoring ST to use subprocess rather than sh for host.exec.
=> Fixed test_arg_parsing.py ST.

README.md, calico_containers/adapter/diags.py, calico_containers/calicoctl.py, calico_containers/tests/st/test_diags.py, docs/Orchestrators.md, docs/Troubleshooting.md
Fixes #149, now diags are placed in a /diagnostics folder before it is gzipped.
=> Converted bash diagnostics code into python, moved into subfolder

calico_containers/pycalico/netns.py, calico_containers/tests/st/docker_host.py
This commit should introduce no functional changes
=> Cleanup code ready for merge to master

Dockerfile, build_calicoctl/Dockerfile, calico_containers/calicoctl.py, calico_containers/pycalico/requirements.txt, image/base.sh, image/buildconfig, image/cleanup.sh, image/install.sh, image/my_init, image/system_services.sh, node_filesystem/README.md
Reduce calico/node from ~500MB to ~250MB
=> Smaller docker image

calico_containers/adapter/diags.py
=> In diags, only copy /var/log/calico if it already exists

calico_containers/tests/st/test_endpoint_commands.py, calico_containers/tests/st/workload.py
=> added STs for endpoint commands

README.md, calico_containers/calicoctl.py
=> updated readme to show new endpoint commands in help text

docs/AdvancedNetworkPolicy.md
@robbrockbank this also removes the default deny from the instructions.
I updated the first part of the example to use the new rules commands but I left the other to show an example of import.
=> Update advanced profile guide with new rules commands.

calico_containers/calicoctl.py
=> Stop enforcing a profile limit of 40 chars

calico_containers/calicoctl.py, calico_containers/pycalico/datastore.py
=> added auto ip detection and hostname collision detection

Dockerfile, Makefile, calico_containers/calicoctl.py, calico_containers/docker_plugin.py, calico_containers/nose.cfg, calico_containers/pycalico/datastore.py, calico_containers/pycalico/diags.py, calico_containers/pycalico/ipam.py, calico_containers/pycalico/netns.py, calico_containers/tests/st/test_add_container.py, calico_containers/tests/st/test_add_ip.py, calico_containers/tests/st/test_arg_parsing.py, calico_containers/tests/st/test_base.py, calico_containers/tests/st/test_bgp_config.py, calico_containers/tests/st/test_diags.py, calico_containers/tests/st/test_duplicate_ips.py, calico_containers/tests/st/test_endpoint_commands.py, calico_containers/tests/st/test_ipv6.py, calico_containers/tests/st/test_mainline.py, calico_containers/tests/st/test_multi_host.py, calico_containers/tests/st/test_no_net_driver.py, calico_containers/tests/st/test_profile_commands.py, calico_containers/tests/st/utils/docker_host.py, calico_containers/tests/st/utils/workload.py, calico_containers/tests/unit/datastore_test.py, calico_containers/tests/unit/docker_plugin_test.py, calico_containers/tests/unit/ipam_test.py, node_filesystem/etc/service/calico-driver/run
This checkin introduces no functional changes
It simplifies the Makefile and leaves everything sane (wheras before it was a mess)
=> Sort out the mess that is our python path

docs/Kubernetes.md
Add docs for demo integration of Calico with Kubernetes.
=> Initial documentation of Kubernetes plugin.

calico_containers/calicoctl.py
=> Convert ETCD_AUTHORITY to an IP address.

docs/Troubleshooting.md
See also https://github.com/Metaswitch/calico-docker/issues/256
=> Add note about NetworkManager to troubleshooting.

calico_containers/calico_ctl/checksystem.py
=> Catch exception with docker not running

docs/bgp.md
First iteration just includes the commands.
Example topologies to follow - but I'll do as a separate PR so that we can at least get the commands documented.
=> Add BGP documentation

calico_containers/calico_ctl/node.py, calico_containers/pycalico/datastore.py, calico_containers/tests/unit/datastore_test.py, docs/etcdStructure.md, node_filesystem/conf.d/bird.toml, node_filesystem/conf.d/bird6.toml, node_filesystem/templates/bird.cfg.template, node_filesystem/templates/bird6.cfg.template
There is a follow on part to this - to update the RR image with the new paths.  That PR will follow.
=> Move BGP configuration to its own sub-tree under calico

calico_containers/calico_ctl/profile.py, calico_containers/pycalico/datastore_datatypes.py, calico_containers/tests/unit/datastore_test.py
=> Fix profile rule add without CIDRs

Dockerfile, Makefile, calico_containers/libnetwork_plugin/datastore_libnetwork.py, calico_containers/libnetwork_plugin/docker_plugin.py, calico_containers/nose.cfg, calico_containers/pycalico/datastore.py, calico_containers/pycalico/datastore_datatypes.py, calico_containers/tests/st/test_multi_host.py, calico_containers/tests/st/utils/docker_host.py, calico_containers/tests/st/utils/network.py, calico_containers/tests/st/utils/workload.py, calico_containers/tests/unit/datastore_libnetwork_test.py, calico_containers/tests/unit/docker_plugin_test.py, docs/etcdStructure.md, node_filesystem/etc/service/calico-driver/run
I'll squash and sort out a better commit message before I merge.
The aim is to get this in today, so please start giving me all feedback but noting if I can defer applying it until after I merge to master.
=> Rewrite libnetwork plugin

calico_containers/libnetwork_plugin/docker_plugin.py, calico_containers/pycalico/datastore_datatypes.py, calico_containers/tests/unit/datastore_libnetwork_test.py, calico_containers/tests/unit/datastore_test.py, calico_containers/tests/unit/docker_plugin_test.py
Added more UTs for libnetwork.
I have currently added pragmas to not count the veth stuff.  I'll sort that out when we move it to netns.
=> Add UTs for covering libnetwork

calico_containers/calico_ctl/pool.py, calico_containers/calico_ctl/utils.py, calico_containers/tests/unit/calicoctl_test.py
=> Add ability to specify ip pool range

calico_containers/calico_ctl/bgp.py, calico_containers/calico_ctl/container.py, calico_containers/calico_ctl/node.py, calico_containers/calico_ctl/pool.py, calico_containers/calico_ctl/status.py, calico_containers/calico_ctl/utils.py, calico_containers/libnetwork_plugin/docker_plugin.py, calico_containers/pycalico/datastore.py, calico_containers/pycalico/ipam.py, calico_containers/tests/unit/calicoctl_test.py, calico_containers/tests/unit/datastore_test.py, calico_containers/tests/unit/docker_plugin_test.py
Removed check_ip_version utils function.
=> Changed all string references of v4/v6 to integer representation. 

build_calicoctl/requirements.txt, calico_containers/tests/unit/calicoctl_test.py
Also made changes to check_ip_version function to handle exception and facilitate testing
=> Added unit tests for calicoctl utils functions

calico_containers/calico_ctl/diags.py
=> Diags felix stats

calico_containers/calico_ctl/node.py
Switched get_host_ips to use subprocess instead of sh since sh was returning blank responses on fedora and subprocess works cross platform. Also updated get_host_ips so it swallows exceptions, allowing 'calicoctl node' to continue with the node creation even if the IP check fails
=> Made calico_ctl.node.get_host_ips fail-safe

calico_containers/calico_ctl/container.py, calico_containers/libnetwork_plugin/docker_plugin.py, calico_containers/pycalico/datastore.py, calico_containers/pycalico/datastore_datatypes.py, calico_containers/pycalico/netns.py, calico_containers/tests/unit/datastore_test.py, calico_containers/tests/unit/docker_plugin_test.py
=> Move libn veth to netns

calico_containers/integrations/kubernetes/calico_kubernetes.py
=> improved kubernetes plugin logging

calico_containers/calico_ctl/container.py
=> Fix container ip add command parameters

node_filesystem/templates/bird.cfg.template, node_filesystem/templates/bird6.cfg.template
=> Configure bird to only log state output

README.md, calico_containers/calico_ctl/node.py, docs/Orchestrators.md, docs/getting-started/VagrantCoreOS.md, docs/getting-started/VagrantUbuntu.md, docs/getting-started/default-networking/EnvironmentSetup.md, docs/getting-started/default-networking/cloud-config/user-data-first, docs/getting-started/default-networking/cloud-config/user-data-others, docs/getting-started/default-networking/vagrant-ubuntu/Vagrantfile, docs/getting-started/libnetwork/EnvironmentSetup.md, docs/getting-started/libnetwork/cloud-config/user-data-first, docs/getting-started/libnetwork/cloud-config/user-data-others, docs/getting-started/libnetwork/vagrant-ubuntu/Vagrantfile, docs/getting-started/powerstrip/CalicoSwarm.md, docs/getting-started/powerstrip/EnvironmentSetup.md, docs/getting-started/powerstrip/cloud-config/user-data-first, docs/getting-started/powerstrip/cloud-config/user-data-others, docs/getting-started/powerstrip/vagrant-ubuntu/Vagrantfile, docs/kubernetes/KubernetesIntegration.md, docs/kubernetes/README.md, image/install.sh
Fix powerstrip version v0.4.8 refs to v0.4.9
=> Update github URLs Metaswitch->projectcalico

calico_containers/calico_ctl/node.py
Move calico-kubernetes references out of calico-docker
=> Update kube plugin ref

calico_containers/calico_ctl/diags.py, calico_containers/tests/unit/diags_test.py, docs/Orchestrators.md, docs/Troubleshooting.md
=> Remove curl from diags collection

calico_containers/calico_ctl/container.py, calico_containers/calico_ctl/endpoint.py, calico_containers/tests/st/bgp/test_bgp_config.py, calico_containers/tests/st/bgp/test_route_reflector_cluster.py, calico_containers/tests/st/bgp/test_single_route_reflector.py, calico_containers/tests/st/no_orchestrator/test_container_to_host.py, calico_containers/tests/st/no_orchestrator/test_mainline_multi_host.py, calico_containers/tests/st/no_orchestrator/test_mainline_single_host.py, calico_containers/tests/st/test_profile.py, docs/getting-started/default-networking/Demonstration.md, docs/getting-started/powerstrip/Demonstration.md
- Add endpoint show (replaced endpoint-id show)
- Add profile add/remove/set commands
=> Update calicoctl container commands

build_calicoctl/requirements.txt, calico_containers/calico_ctl/container.py, calico_containers/calico_ctl/node.py, calico_containers/calico_ctl/utils.py, calico_containers/requirements.txt, calico_containers/tests/unit/container_test.py, image/install.sh
Just putting this up here to get a test run.
=> Allow calicoctl container add to take namespace path

calico_containers/calico_ctl/config.py, calico_containers/calicoctl.py, node_filesystem/etc/calico/felix.cfg, node_filesystem/templates/bird.cfg.template, node_filesystem/templates/bird6.cfg.template
Need to write UTs - but IMO I wouldn't let this prevent us merging.
=> Add general configurability of BIRD and Felix

calico_containers/calico_ctl/node.py, calico_containers/tests/unit/node_test.py
[Rkt Plugin](https://github.com/projectcalico/calico-rkt)
TODO:
=> Install the calico_rkt plugin with calicoctl node --rkt

docs/kubernetes/KubernetesIntegration.md
In regards to https://github.com/projectcalico/calico-kubernetes/pull/24
=> Doc update: default_policy env variable

docs/kubernetes/KubernetesPolicy.md
Sync with [calico-kubernetes/pull/#25](https://github.com/projectcalico/calico-kubernetes/pull/25)
=> Doc Update: Namespace Kubernetes Annotation Key

node_filesystem/etc/calico/felix.cfg
=> Tell felix not to log to file.

calico_containers/calico_ctl/ipam.py, calico_containers/calicoctl.py
release IP - to release an IP address
info IP - to get attributes for an IP
Fixes #492 and #436
=> Add basic calicoctl ipam commands

.gitignore, Makefile, calico_containers/calico_ctl/container.py, calico_containers/calicoctl.py, calico_containers/tests/st/no_orchestrator/test_add_autoassigned_ip.py, calico_containers/tests/unit/container_test.py
This is almost exactly the same as #506, but with a few extra bits. We clearly had the same idea in mind! Great minds.
I'm still adding a few more tests, but since there's already another PR for the same type of change, I thought I would throw mine up for discussion. I don't expect the tests to pass yet.
=> Adding auto_assigning IP logic to containers

calico_containers/calico_ctl/config.py
Fixes #527 
Tim - just a note that this change might need reflecting in your calicoctl docs, so you might as well review it.
=> Logging doc was incorrect

calico_containers/calico_ctl/checksystem.py, calico_containers/calico_ctl/node.py, calico_containers/calico_ctl/utils.py, calico_containers/tests/unit/checksystem_test.py, calico_containers/tests/unit/node_test.py
+ Fix #537
+ Add the checksystem --libnetwork flag
+ Fix UTs for checksystem/node
=> Check for docker API v1.21 if using libnetwork

calico_containers/calico_ctl/checksystem.py, calico_containers/calico_ctl/node.py, calico_containers/calico_ctl/utils.py, calico_containers/tests/unit/checksystem_test.py, calico_containers/tests/unit/node_test.py
+ Fixes #536
+ node_start now sets up ip forwarding with sysctl
+ Reconfigure UTs
=> Remove check_ip_forwarding from check_system

Dockerfile, calico_containers/requirements.txt, image/install.sh
It contains only a single line.
=> Remove requirements.txt

calico_containers/calico_ctl/node.py, calico_containers/calico_ctl/utils.py, calico_containers/tests/unit/node_test.py, calico_containers/tests/unit/utils_test.py
=> Allow specification of Kubernetes plugin version

calico_containers/calico_ctl/node.py
=> Use -a flag to install all modules

docs/kubernetes/AWSIntegration.md, docs/kubernetes/KubernetesIntegration.md, docs/kubernetes/KubernetesPolicy.md, docs/kubernetes/README.md
+ Complete guide for configuring an existing AWS-Kube cluster to use Calico
+ Modify existing Kube docs for clarity, accuracy
=> AWS Kubernetes Integration Doc

README.md
Make them consistent.
Add
- IRC
- Layers
- Docker pulls
=> Update our shields

calico_containers/calico_ctl/checksystem.py, calico_containers/calico_ctl/endpoint.py, calico_containers/calico_ctl/pool.py, docs/calicoctl.md, docs/calicoctl/bgp.md, docs/calicoctl/checksystem.md, docs/calicoctl/config.md, docs/calicoctl/container.md, docs/calicoctl/diags.md, docs/calicoctl/endpoint.md, docs/calicoctl/ipam.md, docs/calicoctl/node.md, docs/calicoctl/pool.md, docs/calicoctl/profile.md, docs/calicoctl/status.md, docs/calicoctl/version.md
Documentation explaining how each calicoctl command works.
**Documentation command TODOs**
=> Calicoctl Documentation

docs/getting-started/VagrantCoreOS.md, docs/getting-started/VagrantUbuntu.md, release-scripts/do_release.py
@tomdee - noticed some instructions that need to be updated for a specific release.  Can you review and hopefully merge before you do a release?
=> Fix release instructions for Vagrant installs

docs/getting-started/libnetwork/cloud-config/user-data-others
Tim,
quick review - rogue bad line in cloud config that should have been removed.  
Rob
=> Remove bad line from cloud config

Makefile, docs/getting-started/VagrantUbuntu.md, docs/getting-started/libnetwork/EnvironmentSetup.md, docs/getting-started/libnetwork/cloud-config/user-data-first, docs/getting-started/libnetwork/cloud-config/user-data-others, docs/getting-started/libnetwork/vagrant-ubuntu/Vagrantfile
And remove old references to consul
=> Update to new docker release - DO NOT MERGE

calico_containers/calico_ctl/checksystem.py, calico_containers/calico_ctl/connectors.py, calico_containers/calico_ctl/node.py, calico_containers/calico_ctl/utils.py, calico_containers/tests/unit/checksystem_test.py, calico_containers/tests/unit/node_test.py
=> Check etcd is up and has the correct version

Makefile, calico_containers/calicoctl.py, docs/Troubleshooting.md, docs/calicoctl.md, docs/getting-started/default-networking/EnvironmentSetup.md, docs/getting-started/default-networking/cloud-config/user-data-first, docs/getting-started/default-networking/cloud-config/user-data-others, docs/getting-started/default-networking/vagrant-ubuntu/Vagrantfile, docs/getting-started/libnetwork/EnvironmentSetup.md, docs/getting-started/libnetwork/cloud-config/user-data-first, docs/getting-started/libnetwork/cloud-config/user-data-others, docs/getting-started/libnetwork/vagrant-ubuntu/Vagrantfile, docs/kubernetes/KubernetesPolicy.md
2379 is the new "official" port
=> Update etcd port from 4001 to 2379

docs/getting-started/default-networking/cloud-config/user-data-first, docs/getting-started/libnetwork/cloud-config/user-data-first
=> Remove duplicate etcd addresses

README.md, docs/mesos/DockerizedDeployment.md, docs/mesos/PrepareCoreServices.md, docs/mesos/PrepareHosts.md, docs/mesos/README.md
Includes README file and Spike's Dockerized Guide moved from the calico-mesos repo.
=> Create mesos documentation directory

calicoctl/calico_ctl/node.py, calicoctl/tests/unit/node_test.py
=> Correct typo in restart policy

release-scripts/do_release.py, release-scripts/utils.py
=> Add some more automation to release script

docs/getting-started/libnetwork/EnvironmentSetup.md
=> Update libnetwork environment setup to document cluster store requirement

calicoctl/calico_ctl/endpoint.py, calicoctl/calico_ctl/profile.py, calicoctl/calico_ctl/utils.py, calicoctl/tests/unit/profile_test.py, calicoctl/tests/unit/utils_test.py, docs/getting-started/libnetwork/EnvironmentSetup.md
This is part of https://github.com/projectcalico/libcalico/pull/53
=> Move validation function to libcalico

docs/calicoctl/node.md, docs/getting-started/libnetwork/Demonstration.md
Update our documentation and demo instructions for the new Calico libnetwork ipam driver.
=> Update documentation to describe IPAM driver

docs/mesos/README.md
Improve readability by numbering required steps, lettering choice steps, and adding slightly more information on what each guide contains.
=> Update mesos readme

calicoctl/calico_ctl/__init__.py, calicoctl/calico_ctl/node.py, release-scripts/do_release.py, release-scripts/utils.py
- Add versions to __init__.py
- Add dry-run option
- Allow all git command to be run automatically
- Allow the cwd to be different to the script directory
=> Release script improvements.

docs/mesos/ManualInstallCalico.md, docs/mesos/ManualInstallNetmodules.md, docs/mesos/PrepareCoreServices.md, docs/mesos/PrepareHosts.md, docs/mesos/README.md, docs/mesos/RpmInstallCalico.md
Improved mesos documentation, added info on manually compiling netmodules
=> Improve Mesos Documentation

calicoctl/calicoctl.py
=> Add signal handler for keyboard interrupts in calicoctl

calico_node/Dockerfile
As proof, I hooked dockerhub builds up for my fork. Before this commit, failure:
https://hub.docker.com/r/djosborne/calico-node/builds/bafgvbz6shqtfsmc6zwh22e/
After this commit, success!:
https://hub.docker.com/r/djosborne/calico-node/builds/bqyfog8v5sh54x7wrvoijhm/
=> Fix pathing issue introduced in Dockerfile

docs/etcdStructure.md
=> Add new IPAM data to etcd structure doc

calicoctl/calico_ctl/profile.py, calicoctl/calico_ctl/utils.py, calicoctl/tests/unit/profile_test.py, calicoctl/tests/unit/utils_test.py
=> Add ICMPv6 support to calicoctl profile rules

calicoctl/calico_ctl/status.py, tests/st/test_status.py
=> calicoctl status exits with 1 on error

calicoctl/calico_ctl/node.py, calicoctl/tests/unit/node_test.py
=> Filter out additional bridge interfaces

calicoctl/calico_ctl/container.py
The main change here is to move a line inside the try block.  The rest is just some minor markups.
Fixes #715
=> Ensure IP deleted if node was not started when using container add

calicoctl/calico_ctl/status.py, docs/calicoctl/status.md
=> Add AS number and IP address to BGP details

docs/mesos/ManualInstallCalicoMesos.md
to use master instead of integration/0.26 as that branch has been merged to master
=> Update netmodules source 

calicoctl/calico_ctl/node.py, calicoctl/tests/unit/node_test.py
This allows a host to originate traffic to workloads that need to be reached over IPIP.
Still need to:
Fixes #426
=> Allocate an IPIP tunnel IP address from calico node.

calicoctl/calicoctl.py
Moved to a separate PR so I can clean up the commits on my IPIP one.
=> Avoid squelching AttributeError raised from the command itself.

calicoctl/calico_ctl/node.py, calicoctl/tests/unit/node_test.py
=> Add more filters to interface names for IP guessing

docs/calicoctl/pool.md
=> Correct docs typo: --ip to --ipip

docs/cni/kubernetes/AWS.md
Ran through the AWS guide and made a few changes to make it easier to follow, fixed an SSH issue.
=> Various fixes to k8s AWS guide

calicoctl/calico_ctl/node.py, calicoctl/calico_ctl/status.py
And allow users to choose their own image
=> Fix status command

calicoctl/calico_ctl/diags.py, calicoctl/tests/unit/diags_test.py
=> Add more diags and fix broken journalctl call

calicoctl/calico_ctl/node.py, docs/cni/rkt/Vagrantfile, docs/cni/rkt/cloud-config/master-config.yaml, docs/cni/rkt/cloud-config/node-config.yaml
=> Use new stage1 argument when running rkt node.

calicoctl/calico_ctl/pool.py, calicoctl/tests/unit/pool_test.py
=> Add check for bad pool size when adding pools with calicoctl

Makefile, calicoctl/tests/unit/node_test.py
=> Mock out modprobe calls in Unit Tests

calicoctl/calico_ctl/status.py
=> Set enforce_root() when running calicoctl status getting bird info

calicoctl/calico_ctl/node.py
=> Require calicoctl node/node stop to be run as root

calicoctl/calico_ctl/node.py, docs/cni/rkt/README.md
- Use correct image for precached calico/node
- Add policy to demo script
=> Update rkt demo

docs/calico-with-docker/docker-network-plugin/README.md
=> Add docs note for creating libnetwork containers with the --ip flag

README.md, docs/calico-with-docker/docker-network-plugin/CalicoAsService.md
=> Add doc explaining calico-libnetwork as a systemd process

calicoctl/calico_ctl/diags.py
=> Force calicoctl diags to run as root

docs/FAQ.md, docs/calico-with-docker/AWS.md, docs/calico-with-docker/docker-network-plugin/README.md, docs/calico-with-docker/without-docker-networking/README.md, docs/cni/kubernetes/AWS.md, docs/cni/kubernetes/GCE.md, docs/cni/kubernetes/VagrantCoreOS.md, docs/cni/kubernetes/cloud-config/master-config-ipip.yaml
I think this covers all the relevant docs, but it's possible I've missed some (particularly if there's anything outside this repository).
=> Update AWS docs to use Disable Source/Dest. Check instead of IP-in-IP

calicoctl/calico_ctl/node.py, calicoctl/tests/unit/node_test.py
=> Quit calicoctl node command if docker fails

calicoctl/calico_ctl/node.py, calicoctl/tests/unit/node_test.py
=> Set nf_conntrack_max during calicoctl node

calicoctl/calicoctl.py
=> Remove SSL todo as we've upgraded Python

calicoctl/calico_ctl/node.py, calicoctl/tests/unit/node_test.py
=> Add node show command and allow removing any node from cluster

calico_test/tests/st/test_base.py, calicoctl/calico_ctl/container.py, calicoctl/calico_ctl/ipam.py, calicoctl/calico_ctl/node.py, calicoctl/calico_ctl/pool.py, calicoctl/tests/unit/container_test.py, calicoctl/tests/unit/node_test.py, calicoctl/tests/unit/pool_test.py, tests/st/no_orchestrator/test_manage_pools.py, tests/st/test_pool.py
=> Fix IP Pool deletion to correctly remove block affinity

calicoctl/startup.py
=> Ignore flannel bridge when getting node IP

calicoctl/calico_ctl/node.py, calicoctl/tests/unit/node_test.py, docs/calicoctl/node.md
=> Add --no-pull option to calico node command

calicoctl/calico_ctl/pool.py, calicoctl/tests/unit/pool_test.py
=> Reject pools that overlap with existing pools

calico_node/filesystem/startup.py, calicoctl/calico_ctl/node.py, calicoctl/tests/unit/node_test.py, docs/calicoctl/node.md
=> Use NO_DEFAULT_POOLS env var to skip default pool creation

docs/cni/kubernetes/stars-demo/README.md, docs/cni/kubernetes/stars-demo/manifests/backend.yaml, docs/cni/kubernetes/stars-demo/manifests/client.yaml, docs/cni/kubernetes/stars-demo/manifests/frontend.yaml, docs/cni/kubernetes/stars-demo/policies/backend-policy.yaml, docs/cni/kubernetes/stars-demo/policies/frontend-policy.yaml, docs/cni/kubernetes/stars-demo/reset.sh, docs/cni/kubernetes/vagrant-coreos/Vagrantfile, docs/cni/kubernetes/vagrant-coreos/cloud-config/master-config.yaml, docs/cni/kubernetes/vagrant-coreos/cloud-config/node-config.yaml, docs/cni/kubernetes/vagrant-coreos/manifests/calico-policy-services.yaml
Cleans up a bit and fixes #872
=> Update stars demo 

docs/cni/kubernetes/AWS.md, docs/cni/kubernetes/GCE.md, docs/cni/kubernetes/KubernetesIntegration.md, docs/cni/kubernetes/NetworkPolicy.md
=> Correct docs references

docs/CalicoAsService.md, docs/ExposePortsToInternet.md, docs/cni/rkt/README.md, docs/cni/rkt/systemd/README.md
Sorry!  Was in a subdirectory when I git added!
=> Correct remaining docs references

calicoctl/calico_ctl/status.py
This is a crude attempt to deal with questions about the "Error connecting to etcd" calicoctl status gives.
=> Mention AUTHORITY/ENDPOINTS when failing to connect to etcd

docs/etcdStructure.md
=> Fix names to be inbound_rules/outbound_rules in etcd struct doc

docs/mesos/vagrant-centos/Vagrantfile
Moved docker provisioner line in mesos vagrant so mesos doesn't get upgraded
=> Fix Mesos Vagrant Demo

docs/cni/kubernetes/GCE.md
=> Update GCE default network IP ranges in docs

docs/FAQ.md
Signed-off-by: depay <depay19@163.com>
=> Add FAQ about arp_ignore

docs/bgp.md
Signed-off-by: depay <depay19@163.com>
=> Fix doc about removing node BGP peer

docs/cni/kubernetes/AWS.md, docs/cni/kubernetes/cloud-config/master-config-ipip.yaml, docs/cni/kubernetes/cloud-config/master-config.yaml
These are simply config changes:
- Bump the kubernetes version.
- Add the policy controller.
=> Update AWS guide to install k8s v1.3.0, v1beta1 policy.

docs/cni/kubernetes/README.md
=> Add top-level stars demo link.

calicoctl/calico_ctl/diags.py
=> calicoctl diags: gather ipset list from inside container if it fails outside

docs/calico-with-docker/without-docker-networking/vagrant-ubuntu/Vagrantfile
Fixes https://github.com/projectcalico/calico-containers/issues/1044
Sticking with v3.0.3 because it's shiny.
=> Fix Ubuntu Vagrant demo

docs/mesos/UsageGuideDockerContainerizer.md
=> Added info on launching Marathon <v1.2.0 docker apps

calicoctl/calico_ctl/node.py, calicoctl/tests/unit/node_test.py
=> Always create runtime dir

calico_node/filesystem/allocate-ipip-addr.py, calico_node/filesystem/etc/calico/confd/conf.d/tunl-ip.toml, calico_node/filesystem/etc/calico/confd/templates/tunl-ip.template, tests/st/test_ipip.py
=> Allocate and deallocate tunl

docs/calico-with-docker/without-docker-networking/README.md
Add a reference link to "endpoint" for new users
=> Add reference to "endpoint"

calico_node/filesystem/etc/rc.local, calico_node/filesystem/etc/service/confd/run
=> Replace all etcd nodes in confd args

tests/st/no_orchestrator/test_hostname_override.py
Requires #1106 
This is a test for #1106
=> Add test for hostname override

calico_node/filesystem/startup.py
This gates `calico/node` startup on etcd.  If etcd isn't present when the node container is started, then we wait for it.  This doesn't affect the case where etcd goes down after a while of normal execution.
The idea here is to prevent a number of race condition scenarios when starting a cluster where etcd is not yet available when the node container is started (but will be soon after).
=> Wait for etcd before continuing in node startup.

docs/calicoctl/profile.md
=> Fix calicoctl docs typo

docs/cni/kubernetes/KubernetesIntegration.md, docs/cni/rkt/cloud-config/master-config.yaml, docs/cni/rkt/cloud-config/node-config.yaml
=> Update CNI plugin versions

calicoctl/calico_ctl/node.py
=> Buffer line when looking for startup message.

Makefile
=> Pass LOCAL_IP_ENV to the ST container

Makefile
- Stop etcd at end of test.
- Insert iptables rule to allow access to etcd.  Fixes #1186.
=> Improve ST make targets

Makefile
To have re-configurable CI and test calico code we need to have
an ability to add custom tags to calico node images, by default:
NODE_CONTAINER_NAME=calico/node:latest
Other changes:
* replace path `calico_node` to `$NODE_CONTAINER_DIR`
* get rid of `pwd` command, instead we define SOURCE_DIR as
the place where calico-containers code is located
=> Allow to redefine calico node docker image name

calico_node/calico-bgp-daemon/main.go, calicoctl/calico_ctl/status.py
This PR adds lacking features in GoBGP backend which BIRD backend has.
List of the features
- Global, Node-Specific neighbor support
- Dynamic configuration support
- IPv6 support
=> Add lacking features in gobgp backend

calicoctl/calico_ctl/profile.py
Fixes incorrect docstring example in calicoctl profile command
=> Minor doc fix for #1196

test/all-no-profile.yaml, test/all.yaml, test/policy-icmp-bad.yaml, test/policy.yaml
part of libcalico-go [#183](https://github.com/projectcalico/libcalico-go/issues/183)
https://github.com/projectcalico/libcalico-go/pull/238 needs to get merged before this
=> [test files] Rename !X fields in API to be notX

calicoctl/commands/apply.go, calicoctl/commands/argutils/args.go, calicoctl/commands/argutils/validate.go, calicoctl/commands/clientmgr/client.go, calicoctl/commands/config.go, calicoctl/commands/create.go, calicoctl/commands/delete.go, calicoctl/commands/get.go, calicoctl/commands/ipam.go, calicoctl/commands/ipam/release.go, calicoctl/commands/ipam/show.go, calicoctl/commands/node.go, calicoctl/commands/node/checksystem.go, calicoctl/commands/node/diags.go, calicoctl/commands/node/permissions.go, calicoctl/commands/node/run.go, calicoctl/commands/node/status.go, calicoctl/commands/replace.go, calicoctl/commands/resources.go, glide.lock
This command shells out to run Docker, can also be dry-run to just output the command.
Currently testing this - but worth putting up for review now.
Since there is no monitoring after spawning the container, I'll need to include in the docs about checking calico-node is running after.
=> Add node run command

Makefile, RELEASING.md
=> Add a darwin make target for calicoctl

calicoctl/commands/config.go, calicoctl/commands/node/run.go, glide.lock
This requires a corresponding libcalico-go change to be merged.
=> Add generic felix config option

calicoctl/resourcemgr/profile.go
=> Fix tags placement

calico_node/startup.py
=> Export startup variables

Makefile
Cut wasn't working well when there were a variable number of spaces
between words
=> Use awk instead of cut

calico_node/startup.py, calicoctl/commands/node/run.go
=> Allow calico/node to not override node resource parms if AS, IP or IP6 options are not specified

Makefile
=> Update bird image to v0.2.0-rc1

calicoctl/commands/node/run.go
=> Add a warning when downloading the docker image

calicoctl/commands/get.go, calicoctl/commands/printer.go, calicoctl/commands/resources.go, calicoctl/resourcemgr/node.go
=> Print global ASN rather than blank

calicoctl/commands/node/status.go, glide.lock, glide.yaml, tests/st/bgp/test_backends.py
[This PR](https://github.com/projectcalico/calico-bgp-daemon/pull/1) must be merged before this get merged.
=> Add support for showing status of calico-bgp-daemon

Makefile
Fixes #1375 
Build process uses containerized builds which did not pass in the "overridable" environments.  These are now all being passed through.
=> Add envs to containerized binary build

Makefile, calico_node/filesystem/etc/rc.local, calico_node/startup.go, glide.lock, glide.yaml
Initial intent is to create a new startup.go and migrate pieces of startup.py over to it.
First bit to migrate is the ClusterGUID.
=> Start moving to startup.go

Makefile
=> Bump python build container to 0.19.0

calicoctl/commands/node/run.go
=> add CALICO_LIBNETWORK_IFPREFIX config flag to calicoctl node run

Makefile, RELEASING.md
=> windows build with .exe

calicoctl/commands/resources.go, glide.lock, glide.yaml
Fixes #1405 
Pre-req: https://github.com/projectcalico/libcalico-go/pull/302
=> Better resource error message

CONTRIBUTING.md, Makefile, README.md, calico_node/filesystem/etc/calico/confd/templates/README.md, calicoctl/Dockerfile.calicoctl.build, calicoctl/calicoctl.go, calicoctl/commands/apply.go, calicoctl/commands/config.go, calicoctl/commands/create.go, calicoctl/commands/delete.go, calicoctl/commands/get.go, calicoctl/commands/ipam.go, calicoctl/commands/ipam/release.go, calicoctl/commands/ipam/show.go, calicoctl/commands/node/run.go, calicoctl/commands/node_linux.go, calicoctl/commands/printer.go, calicoctl/commands/replace.go, calicoctl/commands/resources.go, glide.yaml, tests/st/bgp/test_backends.py
repo-wide search and replace of calico-containers with calicoctl
Minor tweaks to the CONTRIBUTING.md doc - but I don't want to get hung up on other doc rewriting with this PR.
=> Update file paths with new git repo name

Makefile
Useful for testing Felix changes: forces an update of Felix and ensures that calico/node gets rebuilt with the new Felix.
Usage:
make update-felix FELIX_CONTAINER_NAME=calico/felix:<release>
=> Add 'update-felix' target to Makefile.

Makefile
Have one less job (remove the -st one)
Stop listening on 4001
=> Makefile: Clean up our use of etcd

calicoctl/commands/node/run.go
See related https://github.com/projectcalico/calico/pull/419
=> Use calico/node image from quay.io

tests/st/utils/workload.py
adding support for asym TCP testing get_tcp_asym_function and check_can_tcp_asym
=> Add tcp async support

Makefile, Makefile.calico-node, Makefile.calicoctl
Also cleaned up some PHONY statements from the main Makefile
=> Makefile: Split the ut's make target into a ctl and node

Makefile, Makefile.calico-node, Makefile.calicoctl, RELEASING.md
=> Smoother release process take 2

calico_node/filesystem/sbin/versions
```
$ docker run calico/node versions         
confd 0.11.0-dev
BIRD version 1.5.0
libnetwork-plugin: v1.0.0
calico-bgp-daemon: v0.1.2
Felix:
Version:            2.0.3
Full git commit ID: 270de76360ce9230356df7a8d28821ef85d74bc5
Build date:         2017-01-31T02:40:10+0000
```
=> calico/node: Add versions command

Makefile.calico-node, calico_node/startup/startup.go, calico_node/startup/startup_test.go
This PR is addressing Issue #1445 
Should I be adding a flag to calicoctl to set the default pools too?
=> Configure default pools through Env Var

calicoctl/commands/node/run.go
=> bugfix: mount etcd key, cert and CA separately

Makefile.calico-node, Makefile.calicoctl, glide.lock, glide.yaml, tests/st/policy/test_felix_gateway.py
- libcalico-go rev should fix #1498 
- Felix rev should fix #1492 so I have unskipped those tests.
=> Rev libcalico-go to v1.0.3 and Felix to 2.1.0-rc3

calico_node/startup/startup.go, calico_node/startup/startup_test.go
=> Fix WAIT_FOR_DATASTORE so it breaks when connected.

Makefile.calico-node, calico_node/filesystem/etc/rc.local, calico_node/startup/autodetection/filtered.go, calico_node/startup/autodetection/interfaces.go, calico_node/startup/autodetection/reachaddr.go, calico_node/startup/startup.go, calicoctl/commands/node/run.go, tests/st/calicoctl/test_autodetection.py, tests/st/calicoctl/test_node_status.py, tests/st/utils/docker_host.py
Fixes #873
Documentation covered by https://github.com/projectcalico/calico/issues/494
=> Add IP autodetection methods:  can-reach and interface

tests/st/utils/utils.py
Helps to prevent gabled output when running multi-threaded tests.
=> Restore terminal flags after running a command.

.gitignore, Makefile.calico-node, Makefile.calicoctl, calico_node/filesystem/etc/calico/confd/templates/bird_ipam.cfg.template, tests/st/calicoctl/test_ipip.py, tests/st/utils/docker_host.py
=> Check for presence of IPIP mode field before checking value

calico_node/startup/startup.go, calico_node/startup/startup_test.go, glide.lock, glide.yaml
- IPIP env var only applies to IPv4, renamed as appropriate
- Check IPIP env var for validity
- Check IP Pool size
- Check Ipv4 var has v4 Address and Ipv6 var has v6 Address
- Added tests for the above
I believe these changes address #1539 #1537 #1534
=> Fix IPIP env var and add several checks

calico_node/filesystem/etc/rc.local
=> Allow disabling felix

calico_node/filesystem/etc/rc.local
I believe this addresses #1531
=> Ignore failure to remove nonexistent log folders

glide.lock, glide.yaml
=> Rev libcalico-go

tests/st/calicoctl/test_default_pools.py
Will not pass CI until https://github.com/projectcalico/calicoctl/pull/1542 is merged (or else fixes for #1539, #1537, #1534 go in somehow)
=> Add tests of default pool settings

Makefile.calico-node
This reverts commit 1271168a5cdf5ab52c2c7f681837a6fda4772b82.
=> Revert "Use BIRD v0.2.2-alpha1"

tests/st/bgp/test_backends.py, tests/st/bgp/test_global_config.py, tests/st/bgp/test_global_peers.py, tests/st/bgp/test_node_peers.py, tests/st/bgp/test_route_reflector_cluster.py, tests/st/bgp/test_single_route_reflector.py
Signed-off-by: Wataru Ishida <ishida.wataru@lab.ntt.co.jp>
=> ST GoBGP backend

calico_node/startup/startup.go
=> Restore default endpointtohostaction

Makefile.calico-node
Cherry-picking from https://github.com/projectcalico/calicoctl/tree/v1.1.1 's latest commit
=> Bump felix to 2.1.1

calicoctl/commands/node/run.go, tests/st/calicoctl/test_node_run.py
=> Remove ETCD AUTHORITY and SCHEME

calico_node/startup/startup.go
=> Ensure run dir exists and log if not

calicoctl/Dockerfile.calicoctl
=> In calico/ctl put binary in PATH

Makefile.calico-node, Makefile.calicoctl, glide.lock, glide.yaml
- Bumped libcalico-go
- Bumped confd
- Bumped felix
=> Bumping versions

calico_node/allocateipip/allocate_ipip_addr.go
=> Make allocate ipip a no op for KDD

Makefile.calico-node
This is needed for https://github.com/projectcalico/calicoctl/pull/1601
=> Pin GoBGP v0.2.1

calico_node/filesystem/etc/rc.local, tests/st/bgp/test_ipip.py
Signed-off-by: ISHIDA Wataru <ishida.wataru@lab.ntt.co.jp>
=> Add GoBGP to IPIP ST

calicoctl/commands/apply.go, calicoctl/commands/create.go, calicoctl/commands/delete.go, calicoctl/commands/get.go, calicoctl/commands/replace.go
=> Update help message in 'calicoctl get' for easier location of resource types

tests/st/utils/docker_host.py
=> Add extra diagnostics and perform tidy up after error logs

Makefile.calico-node, tests/st/bgp/test_ipip.py
(For the BIRD issue that is documented in https://github.com/projectcalico/bird/pull/37)
=> Test and fix for routes flapping in GCE setup

Makefile.calico-node
Includes fix for memory leak in KDD.
=> Rev Felix to v2.2.2.

tests/st/utils/log_analyzer.py
If an error log is detected at the end of a test, the test code traces out the log and fails the test (unless it's a "known" log that is ignored).
This PR adds the following function:
For each error log that is found, we'll display the logs preceding each error log (up to a max of 300 logs).  This should keep the test diags pretty speedy (doesn't require file uploads) and reduces the amount of log data we'll output.  The main purpose here is to add sufficient context to the errors that we hit.
=> Trace out logs in STs

calico_node/startup/startup.go
Fix automatic directory creation so that it's only performed when necessary.  This removes unnecessary warning logs which occur when these features are disabled.
=> Only create directories if they are needed

Makefile.calico-node
Rev Felix to the upcoming 2.3.0 release version.
=> Rev Felix to 2.3.0.

calicoctl/Dockerfile.calicoctl
Fixes https://github.com/projectcalico/calicoctl/issues/1617
=> Change working directory to /root

calicoctl/commands/node/run.go
Added an option to skip network interfaces specified by regexes so that users can have first-found logic without having to manually specify system/setup specific interfaces to skip by changing the code.
Is dependent upon https://github.com/projectcalico/calico/pull/878 to function properly
Addresses #1555 
Ran this against an image from https://github.com/projectcalico/calico/pull/878 and verified that the specified interfaces were skipped if they matched the regexes given
=> add new interface option for skipping interfaces

calicoctl/commands/version.go
I somehow got in the wrong of the 3 options for Cluster Version and this fixes that.
=> Fix version output

glide.lock, glide.yaml
Part of a series of PRs to standardize the logrus pin across Calico repos.
```release-note
None required
```
=> Update glide logrus, libcalico

glide.lock
A few sentences describing the overall goals of the pull request's commits.
Please include
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR
- links to issues that this PR addresses
```release-note
None required
```
=> Update libcalico to v1.5.1

glide.lock, glide.yaml
Contains fix for https://github.com/projectcalico/calicoctl/issues/1697
```release-note
None required
```
=> Update libcalico to v1.5.3

glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py
Updated libcalico-go for apply on forward.
=> Updated libcalico-go for apply on forward.

glide.lock, glide.yaml, tests/st/utils/data.py
=> Rev libcalico-go to latest 3.0-integration

calicoctl/resourcemgr/resourcemgr.go, tests/st/calicoctl/test_crud.py
=> Apply didn't handle unsupported create operations

glide.lock, glide.yaml
```release-note
None required
```
=> Pin libcalico-go to master

calicoctl/resourcemgr/ippool.go, glide.lock, glide.yaml, test-data/v2/ippool.yaml, tests/st/utils/data.py
A few sentences describing the overall goals of the pull request's commits.
Please include
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR
- links to issues that this PR addresses
```release-note
None required
```
=> update calicoctl for IPIPMode field

glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py
[WIP]. fixup STs. 
```release-note
None required
```
=> bump libcalico-go pin, update STs

calicoctl/commands/version.go
Fixes #1732 
```release-note
None required
```
=> Re-enable Cluster Version and Type output

glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py, tests/st/utils/utils.py
A few sentences describing the overall goals of the pull request's commits.
Please include
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR
- links to issues that this PR addresses
```release-note
None required
```
=> Bcreane bump libcalico go

glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py
Rev libcalico-go to pick up IP Pool fix to delete pool affinities
=> Rev libcalico-go and fix tests

calicoctl/resourcemgr/bgpconfig.go
Fixes #1748
```release-note
Fix calicoctl panic while doing a get on bgpconfig
```
=> Bugfix: calicoctl get bgpconfig command panics

Makefile
Pin the calico/go-build container to v0.9 to pick up go 1.9.2 and CVE fixes.
I do think we should pin to particular releases of go-build to ensure build consistency and repeatability of older builds.
```release-note
None required
```
=> Pin go-build to v0.9 to pick up CVE fixes and go 1.9.2.

glide.lock, glide.yaml, tests/st/utils/data.py
```release-note
None required
```
=> Update libcalico for namespace selector support

calicoctl/resourcemgr/clusterinfo.go, glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py
- Pin libcalico-go to version with ready flag.
- Add column to UI.
- Verify cluster info auto-creation when creating node.
```release-note
None required
```
=> Add ready flag to cluster info.

glide.lock, glide.yaml, tests/st/utils/data.py
=> Automated update of libcalico-go to 83fc14937b8584e65bd6c959c0a85256a2d31e28

calicoctl/commands/printer.go
Reverting a hack to "defaulting" the ASN in some templates
```release-note
None required
```
=> Reverting hardcoding of the default ASN

calicoctl/commands/clientmgr/client.go, calicoctl/commands/printer.go, calicoctl/commands/resources.go, calicoctl/resourcemgr/bgpconfig.go, calicoctl/resourcemgr/bgppeer.go, calicoctl/resourcemgr/clusterinfo.go, calicoctl/resourcemgr/felixconfig.go, calicoctl/resourcemgr/globalnetworkpolicy.go, calicoctl/resourcemgr/hostendpoint.go, calicoctl/resourcemgr/ippool.go, calicoctl/resourcemgr/networkpolicy.go, calicoctl/resourcemgr/node.go, calicoctl/resourcemgr/profile.go, calicoctl/resourcemgr/resourcemgr.go, calicoctl/resourcemgr/workloadendpoint.go, glide.lock, glide.yaml, tests/st/utils/utils.py
Rev libcalico-go and update v2 to v3.
```release-note
None required
```
=> Rev libcalico-go and update v2 to v3

calicoctl/commands/printer.go, calicoctl/commands/resources.go, calicoctl/resourcemgr/bgpconfig.go, calicoctl/resourcemgr/networkpolicy.go, calicoctl/resourcemgr/resourcemgr.go, calicoctl/util/yaml/separator.go, glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py, tests/st/utils/utils.py
```release-note
None required
```
=> Disallow CRUD operations on knp prefixed Network Policy

calicoctl/resourcemgr/resourcemgr.go, glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py, tests/st/utils/utils.py
Pulling from PR #1759 to continue fixing the validation rules after they have been fixed in libcalico-go.
Currently I've pinned libcalico-go to @bcreane PR to fixup the validations in the new API. We'll need to change this to his commit when ready.
```release-note
None required
```
=> Fix STs after turning validation back on

Makefile, glide.lock, glide.yaml
Add pin for google.golang.org/grpc, which was causing glide conflicts.
```release-note
None required
```
=> v1.6.x: Rev libcalico-go and pin go-build to v0.8.

glide.lock
Need to integrate with libcalico-go with support for http and service accounts.
```release-note
None required
```
=> update of libcalico-go to master

calicoctl/commands/node/run.go
```release-note
None required
```
=> Fix hostname detection to use lowercase

calicoctl/resourcemgr/workloadendpoint.go
```release-note
None required
```
=> Update WEP output to hide long name, show pod name

glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py
Revving libcalico-go to pickup the FelixConfig changes, and updating the tests to use the new values.
```release-note
None required
```
=> Revving libcalico-go and updating tests

calicoctl/commands/convert.go, glide.lock, glide.yaml
```release-note
None required
```
=> Fix up import changes for conversion code

tests/st/calicoctl/test_crud.py
Fixes #1766
This PR adds the error messages to check for each failure in the `InvalidData` test so we can be sure that the test is passing for the correct reason.
```release-note
None required
```
=> Updating the InvalidData ST to check the returned error

tests/st/calicoctl/test_convert.py, tests/st/calicoctl/test_upgrade.py
Not sure if we really need this but I thought it wouldn't hurt so I added it.
```release-note
None required
```
=> Add json convert tests

calicoctl/resourcemgr/resourcemgr.go
```release-note
None required
```
=> Removed unused type resourceObj

calicoctl/commands/apply.go, calicoctl/commands/create.go, calicoctl/commands/delete.go, calicoctl/commands/get.go, calicoctl/commands/printer.go, calicoctl/commands/replace.go, calicoctl/resourcemgr/globalnetworkset.go, glide.lock, glide.yaml, test-data/v3/globalnetworkset.yaml, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py, tests/st/utils/utils.py
Plumb through global networks sets into calicoctl.
```release-note
None required
```
=> Add support for GlobalNetworkSets.

glide.lock, glide.yaml
```release-note
None required
```
=> Update libcalico to include KDD HostEndpoints

glide.lock, glide.yaml
It gets rid of some glide warnings
=> glide.yaml: Remove grpc and x/sys pins

Makefile, calicoctl/Dockerfile.calicoctl-s390x, calicoctl/Dockerfile.calicoctl.build-s390x
This PR is raised to provide support for s390x 
Have run 
```bash
ARCH=s390x make test
```
All tests are passing.
=> Added support for s390x

calicoctl/commands/node/run.go
Add /var/lib/calico to the standard list of mounts since the CNI plugin and calico/node now rely on sharing that directory.
```release-note
None required
```
=> Add a mount for /var/lib/calico, which is now required.

glide.lock, glide.yaml
logrus v1.0.5 breaks our logging integration, pin to v1.0.4
```release-note
None required
```
=> Pin logrus to v1.0.4 to avoid breaking bug in v1.0.5.

calicoctl/resourcemgr/resourcemgr.go, tests/st/calicoctl/test_crud.py
```release-note
None required
```
=> dont fallback to Update if operation is NotSupported

calicoctl/resourcemgr/resourcemgr.go, tests/st/calicoctl/test_crud.py
This reverts commit 27503bb80b4332bd2d975fcc561942113623c68c.
Fixes https://github.com/projectcalico/confd/issues/104
```release-note
None required
```
=> Revert "Dont run Update on unsupported Creates"

Makefile, calicoctl/Dockerfile.calicoctl-s390x
Backport of s390x build support #1807
```release-note
Backport s390x build support
```
=> [v3.0] Backport s390x build support

calicoctl/commands/get.go
```release-note
None required
```
=> Fix calicoctl output help text

calicoctl/commands/get.go
#1850 
```release-note
None required
```
=> [release-v3.1] cherry-pick: Fix calicoctl output help text

calicoctl/commands/get.go
#1850 
```release-note
None required
```
=> [release-v3.0] cherry-pick: Fix calicoctl output help text

.circleci/config.yml
=> Tell circle to use bin instead of dist

Makefile
```release-note
None required
```
=> Update Makefile release targets

RELEASING.md
```release-note
None required
```
=> Cleanup RELEASING.md

README.md
update make native build
change 'make binary' to 'make build'
- [1 ] Documentation
```release-note
None required
```
=> update make native build

calicoctl/commands/node/status.go, glide.lock, glide.yaml
```release-note
None required
```
=> Also support new calico-node -felix mode

Makefile
Takes LIBCALICO_VERSION and LIBCALICO_REPO arguments (but defaults them
to sensible values)
=> Makefile: Add update-libcalico target

Makefile
In order to make it MacOS compatible
=> Makefile: Fully containerize update-libcalico

Makefile
And stop setting the arch. It's not needed
=> Makefile: Update go-build to v0.17

Makefile
```release-note
None required
```
=> Fix up which binaries we produce during a release

Makefile
https://github.com/projectcalico/calicoctl/pull/1891
```release-note
None required
```
=> release-v3.2 cherry-pick: Fix up which binaries we produce during a release

Makefile
Syncs use of `CALICO_BUILD` as Makefile var reference to `calico/go-build`, per all other projects. Also fixes broken manifest push.
cc @tomdee
=> Use CALICO_BUILD as standard Makefile var for calico/go-build

calicoctl/commands/node/status.go
https://github.com/projectcalico/calicoctl/pull/1905
```release-note
Fix calicoctl node status handling of terminated processes
```
=> Fix panic in node status when process is terminated

Makefile
```release-note
None required
```
=> Fix release targets

glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py
```release-note
None required
```
=> Fix tests for adjustable block sizes

Makefile
```release-note
None required
```
=> Support local build

Makefile, calicoctl/commands/version.go
```release-note
None required
```
=> Remove build date from binary

Makefile, calicoctl/Dockerfile.calicoctl
Add bare minumum `ci` and `cd` targets so that existing semaphore jobs can still run and validate tests in the `release-v2.6` branch.
```release-note
None required
```
=> Add bare minimum ci and cd targets

Makefile
```release-note
None required
```
=> Build all binaries in releas

Makefile
```release-note
None required
```
=> Automate pushing release binaries

calicoctl/calicoctl.go, calicoctl/commands/label.go, tests/st/calicoctl/test_crud.py
This PR adds a new `calicoctl` command: `calicoctl label`  to add or update a label of resources, fixes #1949. 
```release-note
* add command `calicoctl label` to add or update labels on resources
```
=> add calicoctl label command

glide.lock, glide.yaml, tests/st/utils/data.py
```release-note
None required
```
=> Update libcalico to pull in IPPool node selectors

calicoctl/commands/label.go
Align output to match other calicoctl commands. 
```release-note
None required
```
=> Update calicoctl label output to match other output

calicoctl/resourcemgr/ippool.go, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py, tests/st/utils/utils.py
```release-note
None required
```
=> Update IP pools wide output include node selector

calicoctl/resourcemgr/ippool.go, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py, tests/st/utils/utils.py
Cherry-pick #1957 to v3.5.
```release-note
None required
```
=> Update IP pools output include node selector

glide.lock, glide.yaml
```release-note
None required
```
=> libcalico-go pin update for release v3.5

glide.lock, glide.yaml
```release-note
None required
```
=> libcalico-go pin update for release v3.4

glide.lock, glide.yaml
```release-note
None required
```
=> libcalico-go pin update for release v3.3

glide.lock, glide.yaml
```release-note
None required
```
=> libcalico-go pin update for release v3.2

glide.lock, glide.yaml
```release-note
None required
```
=> Updating libcalico-go pin for v3.1 release

glide.lock, glide.yaml
```release-note
None required
```
=> Updating libcalico-go pin for v3.0 release

Makefile
```release-note
None required
```
=> Correct filename in upload to github

Makefile
```release-note
None required
```
=> Build all binaries as part of release

glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py
Update libcalico-go pin, and also fix up what the STs are expecting for error messages (mostly capitalization)
```release-note
None required
```
=> Update libcalico, fix ST output expectations

README.md, calicoctl/commands/apply.go, calicoctl/commands/create.go, calicoctl/commands/delete.go, calicoctl/commands/get.go, calicoctl/commands/label.go, calicoctl/commands/replace.go, calicoctl/resourcemgr/networkset.go, glide.lock, glide.yaml, test-data/v3/networkset.yaml, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py
Add support for NetworkSets.
```release-note
Add NetworkSets
```
=> Add NetworkSets support

glide.lock, glide.yaml, test-data/v3/ippool.yaml, tests/st/utils/data.py
```release-note
None required
```
=> Update libcalico to include VXLAN changes

calicoctl/commands/convert.go, calicoctl/commands/resources.go, calicoctl/resourcemgr/ippool.go, calicoctl/resourcemgr/resourcemgr.go, tests/st/utils/data.py
Add VXLANMODE to IP pools output.
```release-note
None required
```
=> Add VXLANMODE to IP pools output.

calicoctl/commands/get.go
```release-note
None required
```
=> fixed typo in get.go docs

calicoctl/calicoctl.go, calicoctl/commands/apply.go, calicoctl/commands/convert.go, calicoctl/commands/create.go, calicoctl/commands/delete.go, calicoctl/commands/get.go, calicoctl/commands/ipam.go, calicoctl/commands/ipam/release.go, calicoctl/commands/ipam/show.go, calicoctl/commands/label.go, calicoctl/commands/node/checksystem.go, calicoctl/commands/node/diags.go, calicoctl/commands/node/run.go, calicoctl/commands/node/status.go, calicoctl/commands/node_darwin.go, calicoctl/commands/node_linux.go, calicoctl/commands/node_windows.go, calicoctl/commands/replace.go, calicoctl/commands/resources.go, calicoctl/commands/version.go
```release-note
All error output goes to stderr
```
=> All error messages go to stderr

glide.lock, glide.yaml, tests/st/calicoctl/test_crud.py
```release-note
None required
```
=> Update of libcalico-go

README.md
relates to https://github.com/projectcalico/calicoctl/issues/913
also relates to https://github.com/Homebrew/homebrew-core/pull/39892
=> Add install section for README

calicoctl/commands/printer.go
Fixed unknown value by replacing hardcoded value with default ASN (64512).
```release-note
Show default ASN when no BGP configuration exists
```
=> Fix "Unknown" ASN being shown. 

calicoctl/commands/printer.go
Slight fix to only show default value when we are getting ErrorResourceDoesNotExist.
```release-note
None required
```
=> Fix "Unknown" ASN being shown & error type check

calicoctl/commands/ipam/show.go, tests/fv/ipam_test.go
See https://github.com/projectcalico/calico/pull/2647
=> Improve output for IP attributes

glide.lock, glide.yaml
```release-note
None required
```
=> Rev libcalico-go to 487ec57127d266ef742a9e2553f720c51a2e8928

glide.lock, glide.yaml
```release-note
None required
```
=> Rev libcalico-go to pick up felix config name change.

Makefile
```release-note
None required
```
=> Fix empty GOPATH_LOCAL variable

tests/st/utils/utils.py
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
/kind cleanup by fix misspelled words
```release-note
None required
```
=> fix typos in utils.py: Unxpected -> Unexpected

calicoctl/commands/patch.go
The command docs did not use real world examples, this is now fixed.
```release-note
None required
```
=> Update patch docs to use real spec

Dockerfile.amd64, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x
Update base alpine base image 3.8 -> 3.10
```release-note
None required
```
=> Update alpine image to 3.10

calicoctl/commands/apply.go, calicoctl/commands/create.go, calicoctl/commands/resources.go, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py
* Fix "partial success" message shown with failed Apply
- Update Apply to return multiple errors
* Add test for 'partial success' fix
* Fix "partial success" for Create
```release-note
None required
```
=> Cherry-pick into release-v3.10: Fix erroneous "Partial success" output (#2068)

calicoctl/commands/replace.go
fix  calicoctl replace --help Description error
```release-note
Fix calicoctl replace help text 
```
=> fix  calicoctl replace --help Description error

Makefile
Similar to fixes done in the other calico child repos.
=> Fixing EXTRA_DOCKER_ARGS

README.md
Fixes https://github.com/projectcalico/calicoctl/issues/2063
```release-note
None required
```
=> Remove incorrect REAMDE content

Makefile
Cherry-pick of https://github.com/projectcalico/calicoctl/pull/2092
```release-note
None required
```
=> release-v3.11: Cherry-pick Fix building of binaries (#2092)

glide.lock, glide.yaml
```release-note
None required
```
=> release-v3.8 - Update pins

calicoctl/commands/apply.go, calicoctl/commands/create.go, calicoctl/commands/delete.go, calicoctl/commands/get.go, calicoctl/commands/label.go, calicoctl/commands/patch.go, calicoctl/commands/replace.go, calicoctl/resourcemgr/kubecontrollersconfig.go, calicoctl/resourcemgr/kubecontrollersconfig_test.go, go.mod, go.sum, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py
Signed-off-by: Spike Curtis <spike@tigera.io>
Add support for KubeControllersConfiguration including tests
```release-note
Add support for KubeControllersConfiguration
```
=> Add support for KubeControllersConfiguration

calicoctl/resourcemgr/kubecontrollersconfig_test.go, go.mod, go.sum
Signed-off-by: Spike Curtis <spike@tigera.io>
Update KubeControllersConfiguration to use metav1.Duration
```release-note
None required
```
=> Update KubeControllersConfiguration to use metav1.Duration

go.mod, go.sum, tests/st/calicoctl/test_crud.py
```release-note
None required
```
=> Update libcalico-go pin and update tests

calicoctl/commands/ipam/show.go
```release-note
None required
```
=> Rename configuration option to show-configuration

calicoctl/commands/ipam/show.go
```release-note
None required
```
=> Remove un-necessary extra print.

calicoctl/commands/ipam/show.go
```release-note
None required
```
=> Remove un-necessary extra print. (#2124)

go.mod, go.sum
```release-note
None required
```
=> Update libcalico-go to dda4a7964ffad2dace251d0a8f95c2ba78ec91f8

Makefile
```release-note
None required
```
=> Update go-build to v0.39 [release-v3.14]

Makefile
```release-note
None required
```
=> Update go-build to v0.39 for manifest-tool update

go.sum
```release-note
None required
```
=> Clean go.sum

calicoctl/calicoctl.go
Cherry-pick of https://github.com/projectcalico/calicoctl/pull/2139
```release-note
None required
```
=> Fix the help text for the datastore command

calicoctl/commands/datastore/migrate/import.go, go.mod, go.sum, tests/st/calicoctl/test_migrate.py, tests/st/utils/data.py
Handles the case where a node in the etcd datastore does not reference a valid Kubernetes node. Instead of throwing the error, throw a warning instead while still importing all the other valid resources.
```release-note
None required
```
=> Handle case where a node does not reference a valid K8s node

calicoctl/commands/datastore/migrate/import.go, tests/st/calicoctl/test_migrate.py, tests/st/utils/data.py
Cherry-pick of https://github.com/projectcalico/calicoctl/pull/2143
```release-note
None required
```
=> Fix node bug 3.15

go.mod, go.sum
```release-note
None required
```
=> pin-updates libcalico-go

go.mod, go.sum
Adds knobs for explicitly allowing encap traffic.
```release-note
None required
```
=> Update pins - pick up FelixConfiguration

go.mod, go.sum
Adds knobs for explicitly allowing encap traffic.
```release-note
None required
```
=> [release-v3.16] Update pins - pick up FelixConfiguration

go.mod, go.sum
Adds knobs for explicitly allowing encap traffic.
```release-note
None required
```
=> [release-v3.15] Update pins - pick up FelixConfiguration

calicoctl/commands/datastore/migrate/export.go
Adds the `KubeControllersConfiguration` resource to the datastore migration.
```release-note
Datastore migration commands migrate KubeControllersConfiguration resources.
```
=> Add KubeControllersConfiguration to the datastore migration

go.mod, go.sum
```release-note
None required
```
=> Rev libcalico-go to pick up defaulting fix.

.semaphore/clear_cache.yml, .semaphore/semaphore.yml, .semaphore/update_pins.yml, Makefile
```release-note
None required
```
=> Semaphore v2 migration / add pin update pipeline

Makefile
```release-note
None required
```
=> Build image before CD

go.mod, go.sum, tests/st/calicoctl/test_crud.py
```release-note
None required
```
=> Update pin for BGPPeer password field

go.mod, go.sum, tests/st/calicoctl/test_crud.py
=> Cherry pick BGP password support from master

.semaphore/semaphore.yml
```release-note
None required
```
=> Fix release branch pin update regex (add ^ to start)

calicoctl/calicoctl.go, calicoctl/commands/apply.go, calicoctl/commands/create.go, calicoctl/commands/delete.go, calicoctl/commands/get.go, calicoctl/commands/label.go, calicoctl/commands/patch.go, calicoctl/commands/replace.go, test-data/kubectl-config.yaml, tests/fv/multi_context_test.go, tests/fv/utils/calicoctl.go
Using https://github.com/projectcalico/libcalico-go/pull/1335 this PR adds `--context` argument to calicoctl.
```release-note
None required
```
=> --context support to calicoctl

Makefile, calicoctl/commands/datastore/migrate/export.go, tests/st/calicoctl/test_migrate.py, tests/st/utils/data.py, tests/st/utils/utils.py
This should fix an issue where namespaces and networksets in different namespaces were not being migrated.
```release-note
Fixes bug where namespaced resources were not being migrated across datastores.
```
=> Handle namespaced resources during datastore migration properly

Makefile
```release-note
None required
```
=> Fix version reporting

calicoctl/commands/clientmgr/client.go, calicoctl/commands/crds/decode.go, calicoctl/commands/ipam.go, calicoctl/commands/ipam/check.go, calicoctl/commands/ipam/release.go, calicoctl/commands/node/checksystem.go, calicoctl/commands/node/diags.go, calicoctl/commands/node/status.go, go.mod, tests/fv/multi_context_test.go
- Add's "ipam check" command which does a consistency check against Calico's IPAM data, writes a report.
- Enhance "ipam release" to be able to release inconsistent addresses from the generated report.
```release-note
Add calicoctl ipam check command to check IPAM consistency
```
```release-note
Allow releasing of IP addresses based on output report from calicoctl ipam check command.
```
=> Additional IPAM sub commands

calicoctl/commands/ipam/check.go
```release-note
None required
```
=> Fix docstring for check command

calicoctl/commands/ipam/check.go
Adds some missing help text for `ipam check`.
```release-note
None required
```
=> Add help text for show-all-ips and show-problem-ips

.semaphore/clear_cache.yml, .semaphore/semaphore.yml, .semaphore/update_pins.yml
```release-note
None required
```
=> Add semaphore v2 configuration

calicoctl/commands/node/checksystem.go
Update 
Issue reported here https://github.com/projectcalico/calico/issues/4288
[x] add bootconfig file to the mix of checks
[x] add kernel variables of required modules as a backup
[x] Add option to get the bootconfig override from user input
- Add `compress/gzip` in order to read `/boot/config.tar.gz` included in some linux flavors
- a windows checkfile system
```release-note
Improve calicoctl checksystem's ability to discover kernel dependencies
```
=> Check system update

calicoctl/commands/argutils/validate.go, calicoctl/commands/datastore/migrate/export.go, calicoctl/commands/datastore/migrate/export_test.go, calicoctl/commands/datastore/migrate/import.go, calicoctl/commands/version.go, calicoctl/resourcemgr/bgpconfig.go, calicoctl/resourcemgr/bgppeer.go, calicoctl/resourcemgr/clusterinfo.go, calicoctl/resourcemgr/felixconfig.go, calicoctl/resourcemgr/globalnetworkpolicy.go, calicoctl/resourcemgr/globalnetworkset.go, calicoctl/resourcemgr/hostendpoint.go, calicoctl/resourcemgr/ippool.go, calicoctl/resourcemgr/kubecontrollersconfig.go, calicoctl/resourcemgr/kubecontrollersconfig_test.go, calicoctl/resourcemgr/networkpolicy.go, calicoctl/resourcemgr/networkset.go, calicoctl/resourcemgr/profile.go, calicoctl/resourcemgr/resourcemgr.go, calicoctl/resourcemgr/resourcemgr_test.go, go.mod, go.sum, tests/fv/ipam_test.go, tests/fv/migrate_ipam_test.go, tests/fv/namespace_option_test.go
```release-note
None required
```
=> Replace lib/v3 package with projectcalico/api

Makefile, calicoctl/calicoctl.go, calicoctl/commands/version.go, tests/fv/helper/calico_version_helper.go, tests/fv/ipam_test.go, tests/fv/migrate_ipam_test.go, tests/fv/multi_context_test.go, tests/fv/namespace_option_test.go, tests/fv/utils/calicoctl.go, tests/st/calicoctl/test_flags.py, tests/st/manifests/crd.projectcalico.org_clusterinformations.yaml, tests/st/utils/utils.py
Cherry pick https://github.com/projectcalico/calicoctl/pull/2353 to 3.20
```release-note
None required
```
=> Add client/cluster version mismatch verification

calicoctl/commands/version.go, tests/st/calicoctl/test_flags.py
Cherry pick of #2371 on release-v3.20.
#2371: Skip version mismatch check when CalicoVersion not
=> Automated cherry pick of #2371: Skip version mismatch check when CalicoVersion not

tests/fv/helper/calico_version_helper.go
```release-note
None required
```
=> Add license to calico_version_helper.go

calicoctl/calicoctl.go, tests/st/calicoctl/test_flags.py
Revert error message wording in calicoctl.go
```release-note
None required
```
=> Revert error message

Makefile
Cherry pick of #2385 on release-v3.20.
#2385: Fix release target
=> Automated cherry pick of #2385: Fix release target

calicoctl/commands/version.go, tests/fv/multi_context_test.go
```release-note
None required
```
=> Skip version mismatch check for commands with no API access required

Makefile
This should fix the failing `cd` target.
```release-note
None required
```
=> fix the cd target

Makefile, calicoctl/calicoctl.go, calicoctl/commands/apply.go, calicoctl/commands/common/resources.go, calicoctl/commands/common/version_mismatch.go, calicoctl/commands/convert.go, calicoctl/commands/create.go, calicoctl/commands/datastore/migrate/export.go, calicoctl/commands/datastore/migrate/import.go, calicoctl/commands/datastore/migrate/lock.go, calicoctl/commands/datastore/migrate/unlock.go, calicoctl/commands/delete.go, calicoctl/commands/get.go, calicoctl/commands/ipam/check.go, calicoctl/commands/ipam/configure.go, calicoctl/commands/ipam/release.go, calicoctl/commands/ipam/show.go, calicoctl/commands/label.go, calicoctl/commands/node/checksystem.go, calicoctl/commands/node/diags.go, calicoctl/commands/node/run.go, calicoctl/commands/node/status.go, calicoctl/commands/patch.go, calicoctl/commands/replace.go, calicoctl/commands/version.go, tests/st/calicoctl/test_flags.py
Cherry pick of #2390 on release-v3.20.
#2390: Refactor version mismatch checking to not need argument parsing
=> Automated cherry pick of #2390: Refactor version mismatch checking to not need argument

calicoctl/commands/common/version_mismatch.go
```release-note
None required
```
=> Fix version mismatch error message formatting

go.mod, go.sum, tests/fv/ipam_test.go, tests/fv/migrate_ipam_test.go, tests/st/calicoctl/test_crud.py, tests/st/utils/data.py, tests/st/utils/utils.py
```release-note
None required
```
=> [allowed-use] Set the intended use on IPAM allocations.

Dockerfile.arm64, Dockerfile.armv7, Dockerfile.ppc64le, Dockerfile.s390x, Makefile
Cherry pick of #2415 on release-v3.21.
#2415: Multiarchitectural support
=> Automated cherry pick of #2415: Multiarchitectural support

Makefile
cherry-pick https://github.com/projectcalico/calicoctl/pull/2458
```release-note
None required
```
=> Remove TTY flag from docker exec
