calico.py
master/confd.sh
master/rc.local
node/confd.sh
node/rc.local

Adds an environment variable, ETCD_IP, which specifies the IP to send etcd requests for confd.
Could be a proxy or cluster member (ideally the former). confd has a -nodes arg if you want to specify all of the cluster members directly, but we probably prefer to encourage using a local etcd proxy for flexibility.

Make the etcd repo used by confd configurable.

---

calicoctl.py
requirements.txt

Adds docker-py as a dependency.  We should consider eventually phasing out the sh-based Docker commands we have now.

Use names or IDs for calicoctl addtogroup

---

node/Dockerfile

Missing line continuation was causing 'apt-get' to be parsed as
a new dockerfile command, which fails (without throwing an error).
This caused us to skip the apt-clean step.

Fix formatting error in node Dockerfile.

---

node/root_overlay/adapter/powerstrip-calico.py

Used to just log "__main__", which is not descriptive; now we'll
log "filename.__main__".

Update log format to include the source filename.

---

node/root_overlay/adapter/netns.py

netns didn't handle the case with no default route;
the 'ip route | grep default' call returns 1 if there is no match,
and therefore the check_output call fails.
Fix is to parse the returned 'ip route' output in python instead.
Fixes Metaswitch/calico-docker#23

Fix handling of netns with no default-route.

---

requirements.txt

Latest (2.5.2 & 2.5.3) requests.py interacts badly with pyinstaller.
See
http://stackoverflow.com/questions/28775276/pyinstaller-error-importerror-no-module-named-requests-packages-chardet-sys

Pin requests.py version in requirements.txt

---

README.md
calicoctl.py
datastore.py
master/root_overlay/plugin.py
node/Dockerfile
node/root_overlay/adapter/calico_etcd.py
node/root_overlay/adapter/netns.py
node/root_overlay/adapter/powerstrip-calico.py
node/root_overlay/conf.d/bird6.toml
node/root_overlay/etc/rc.local
node/root_overlay/etc/service/bird6/run
node/root_overlay/templates/bird6.cfg.template

High level changes:
- add commands for IPv6 address pools
- add bird6 to calico-node with Confd configuration
- move to latest calico-felix (including zeroMQ API update for interface names) for proxy NDP config
- program containers with local gateway, rather than default via device directly
- version checking of IP address to program netns correctly

Add support for IPv6 networked containers

---

Dockerfile

This branch from @fasaxc  includes the felix polling workaround, plus fixes to ECMP in Felix.

Update debs to use artifacts from "smc-anycast-and-fixes".

---

calicoctl.py
node/adapter/datastore.py
node/templates/bird.cfg.template
node/templates/bird6.cfg.template
tests/unit/datastore_test.py

Configure AS using 
- etcdctl set /calico/config/bgp_as 64512

Add calicoctl commands for BGP Peers (and configurable AS)

---

node/templates/bird.cfg.template
node/templates/bird6.cfg.template

Previously we applied the same filter to import and export policy,
so only prefixes specified in etcd would be imported.
Relax this restriction, under the assumption that the RR/ToR
will be configured to only export sensible routes to us.

Fix import policy in bird to allow all routes.

---

Dockerfile
node/templates/bird.cfg.template
node/templates/bird6.cfg.template

Add-path is required for Bird to advertise ECMP IPs. If it's not
enabled, Bird will refuse to advertise its route to the ECMP
IP if there's another copy of that route already advertised by
another node.

Upgrade Bird to 1.4.5, and enable BGP add-path.

---

calicoctl.py

Allow an optional interface name to be passed to calicoctl container add

---

node/templates/bird.cfg.template
node/templates/bird6.cfg.template

Extract common config into a template, to reduce duplication
in the bird and bird6 config files.
Retarget of https://github.com/Metaswitch/calico-docker/pull/84, review'd by @spikecurtis

Refactor bird config files to use bgp template.

---

node/adapter/powerstrip-calico.py

This change ensures that we don't accidentally pass `None` to `env_to_dictionary`.
The other option was to do a short-circuit return in `env_to_dictionary`, but I felt like that was a weirdly general solution, so I decided this ternary approach was better.
Resolves #92.

Avoid None being passed to env_to_dictionary

---

README.md
calicoctl.py
run_fvs.sh
tests/fv/add_container.sh
tests/fv/add_ip.sh
tests/fv/arg_parsing.sh
tests/fv/mainline.sh

This is a fix for enhancement #102
See comment in this issue for details of the changes.

Remove unnecessary IPv4/6 options from various calicoctl commands

---

build_calicoctl/requirements.txt
calicoctl.py
node/adapter/netns.py
node/adapter/requirements.txt
tests/fv/mainline.sh

Also introduces some test refactoring,
Currently breaks on circle CI. We should run the tests in a container so it doesn't break...

Use nsenter as it is more generic and faster than docker exec

---

node/templates/bird.cfg.template

Make bird aware of device routes for all non-calico interfaces

---

calicoctl.py
node/adapter/datastore.py
node/adapter/netns.py
node/adapter/powerstrip-calico.py
tests/fv/add_ip.sh
tests/unit/datastore_test.py

This doesn't work yet as it uncovers a bug in Felix where Felix does not update the ARP cache for a MAC change.
See: https://github.com/Metaswitch/calico/issues/549
We could work around it by deleting the endpoint and creating a new endpoint - but I don't like that as it's not an atomic operation.  That said, it would be a simple temporary solution.

Add ability to reinstate networking to container

---

node_filesystem/templates/bird.cfg.template
node_filesystem/templates/bird6.cfg.template

This works around an issue with BIRD that does not handle unnamed protocols when using templates.
The key change here is to add a name to the profiled protocol section.
so
```
protocol bgp  from bgp_template {   ->   protocol bgp bgp_name from bgp_template {
```
This is required to get GR working.  Without this, a reload of BIRD config results in all routes being dropped.
I've named each protocol section according to the IP address of the peer (with . and : replaced with _).

Fix BIRD issue with unnamed protocols using templates

---

build_calicoctl/Dockerfile
create_binary.sh

Fixes
```
Traceback (most recent call last):
File "/usr/local/bin/pyinstaller", line 9, in <module>
load_entry_point('PyInstaller==2.1', 'console_scripts', 'pyinstaller')()
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/main.py", line 86, in run
spec_file = run_makespec(opts, args)
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/main.py", line 40, in run_makespec
spec_file = PyInstaller.makespec.main(args, **opts.__dict__)
File "/usr/local/lib/python2.7/dist-packages/PyInstaller/makespec.py", line 322, in main
specfile = open(specfnm, 'w')
IOError: [Errno 13] Permission denied: '/code/calicoctl.spec'
```
Root cause is that the `create_binary.sh` script mounts the project root as `/code` inside the build container.  However, the user account inside the container may not …

Fix create_binary build permission issues.

---

calico_containers/calicoctl.py
create_binary.sh
run_sts.sh
run_uts.sh

Fixes up python path issues so you can run calicoctl.py from ./calico_containers/ and still build correctly.

Run calicoctl with python

---

README.md
calico_containers/calicoctl.py
calico_containers/tests/st/docker_host.py

Fixes #150, calicoctl now only prints *warnings* for detected issues concerning system dependencies during node creation, but will not cancel the process if it detects them. 
For now, if our system check incorrectly detects issues, the user will just have to read past those warnings knowing that their system is in fact OK. We will have to work towards better detection across host platforms in the future so users won't be bothered with any incorrect messages (see #150).
Additionally, added the `calicoctl checksystem [--fix]` command which will print any detected issues, and will attempt to fix them if the `--fix` flag is provided.

Fixes #150, degrades fatal system dep errors to warnings

---

node_filesystem/templates/bird.cfg.template
node_filesystem/templates/bird6.cfg.template

The device routes switch tells BIRD to export device routes to the kernel.  This isn't required as the underlying network configuration has already set up device routes within the kernel leading to "File Exists" spam in the BIRD log.

Remove device routes from BIRD kernel config.

---

calico_containers/docker_plugin.py
calico_containers/pycalico/datastore.py

Make the endpoint an optional thing, defaulted to None.
Endpoint is broken. We don't know the interface name (libnetwork
decides it) so it shouldn't be a mandatory parameter.

Stop setting the endpoint name since we can't know it.

---

create_binary.sh

docopt-completion writes file to pwd, so cd before running command so output is in the dist directory.

cd to dist directory before running docopt-completion

---

calico_containers/tests/st/docker_host.py
calico_containers/tests/st/test_ipv6.py

In order to get this working, I changed the hardcoded IPv6 address for the
DockerHost to be in a range separate to the container pool.  Otherwise, the
first container would get an IP that conflicted with its own gateway.

Fix test_ipv6.py ST

---

calico_containers/tests/st/docker_host.py
calico_containers/tests/st/test_add_container.py
calico_containers/tests/st/test_add_ip.py
calico_containers/tests/st/test_arg_parsing.py
calico_containers/tests/st/test_base.py
calico_containers/tests/st/test_diags.py
calico_containers/tests/st/test_duplicate_ips.py
calico_containers/tests/st/test_ipv6.py
calico_containers/tests/st/test_mainline.py
calico_containers/tests/st/test_multi_host.py
calico_containers/tests/st/test_no_net_driver.py
calico_containers/tests/st/test_profile_commands.py
calico_containers/tests/st/utils.py

DockerHost becomes a context manager so you can use it like
```
with DockerHost('host') as host:
```
Fixes up existing STs to use this form.

Make DockerHost context manager that cleans up.

---

calico_containers/calicoctl.py

For example: `allow from tag FOO`

Support rule match without protocol.

---

Dockerfile
docs/GCE.md

@robbrockbank This pulls the version of BIRD that I built from my PR and removes the work-around from the instructions: https://github.com/Metaswitch/calico-bird/pull/2
Blocked on @spikecurtis's review of that PR, I suppose.

Disable BIRD's recursive route check for GCE compatibility.

---

calico_containers/adapter/datastore.py
calico_containers/calicoctl.py

We were using strings instead of ints when generating rules and the Rule object was missing support for icmp_code.

Fix ICMP handling in rules/parsing

---

calico_containers/calicoctl.py
calico_containers/tests/st/test_duplicate_ips.py
docs/GettingStarted.md
docs/Troubleshooting.md

- Removed `calicoctl reset`
- Removed `profile member add`
- Changed title of column in `ip_pool_show` from ip-ip to Options
- Updated getting started documentation to use new endpoint command

Calicoctl changes, getting started update

---

calico_containers/calicoctl.py

Oops, @tomdee, @robbrockbank spotted we were already validating those values in validate_arguments.  No point in doing it twice.

Remove duplicate validation.

---

calico_containers/calicoctl.py
calico_containers/docker_plugin.py
calico_containers/pycalico/datastore.py
calico_containers/tests/unit/datastore_test.py

- Replaced references to "docker" in datastore by abstracting with orchestrator
- Modified other functions to use the new and optimized get_endpoints
- Removed obsolete shownodes and get_host functionality
See individual commits for easier view

datastore cleanup

---

calico_containers/calicoctl.py
calico_containers/docker_plugin.py
calico_containers/pycalico/datastore.py
calico_containers/pycalico/netns.py
calico_containers/tests/unit/datastore_test.py

@robbrockbank 
Turns out we were incorrectly setting the `endpoint.workload_id`, but since it wasn't being used by `set_endpoint` we didn't notice it.

Djo update endpoint

---

calico_containers/docker_plugin.py
calico_containers/pycalico/datastore.py
calico_containers/tests/unit/datastore_test.py

We had a TODO from when we'd moved code around.
Reinstate the code and add a UT for it.

Endpoint deletion in Libnetwork plugin

---

docs/AWS.md
docs/CalicoSwarm.md
docs/DigitalOcean.md
docs/GCE.md
docs/Orchestrators.md

The calicoctl version will soon change to work strictly with libnetwork, so the demos that use powerstrip should have a static version of calicoctl that supports powerstrip.

Update demo calicoctl version to be static, not latest

---

build_calicoctl/Dockerfile

Before this fix, the Dockerfile for calico/build had apt-get update and apt-get install on separate RUN lines.  This means Docker can cache the filesystem after the update.
After a few days, the apt-cache from that update gets stale, and an apt-get install tries to pull a discontinued point release of some library, and builds fail.
This fixes that by forcing them all on the same RUN line.

Fix stale APT cache when building calicoctl binary

---

docs/logging.md

The irony that I made a typo in the branch name is not lost on me.

Fix typo in the docs

---

Makefile

The code coverage module requires the /code directory to be
writable, which it won't be if the UID of the user outside the container
doesn't match the UID of the `user` user inside the container.
Running under `user` is only required for pyinstaller, not UTs.

Run UT as root inside the container

---

README.md
docs/GettingStarted.md
docs/Orchestrators.md

Powerstrip is now an archived branch.  Update the GettingStarted page to be specific to libnetwork with ubuntu nodes and reference the ubuntu-vagrant demo as the cluster creation page, rather than coreos which does not currently have libnetwork support in its docker version.

Update docs to reflect libnetwork changes

---

calico_containers/calico_ctl/node.py
calico_containers/calicoctl.py
calico_containers/nose.cfg
calico_containers/tests/unit/node_test.py

This addition allows the Calico service to be more easily integrated with init systems, which start a process and monitor it.  In this case, calicoctl is that process, and shares fate with the calico-node container.

Add --detach=false option, to run calico-node in foreground

---

calico_containers/calico_ctl/profile.py

If a profile is associated with any number of endpoints, prevent the profile from being removed.

Profile cannot be removed if it has endpoints

---

Makefile
docs/Building.md

Fix up Building.md to show how to build the calicoctl image
Close issue #293

Add 'make node' for caliconode.created shortcut

---

calico_containers/tests/st/test_base.py

Is this actually needed?
I get messages like this when running tests
```
nosetests calico_containers/tests/st/test_multi_host.py -sv --nologcapture --with-timer
Run a mainline multi-host test. ... No handlers could be found for logger "sh.command"
```

Remove warning about sh.command logger

---

calico_containers/pycalico/datastore.py
calico_containers/tests/st/test_container_to_host.py
calico_containers/tests/unit/datastore_test.py

Starting in Felix v0.25, the default behaviour is to prevent
endpoints from reaching thier local host IP.  However, this is
required for common containerized environments like Mesos,
where the containerized executor exchanges messages with a
Mesos Slave process on the host.
This change reverts Felix to the pre-0.25 behaviour by setting
a configuration field in etcd.
It also includes an ST for regression testing.

Allow containers to reach the host.

---

calico_containers/calico_ctl/node.py

calicoctl now makes the kubernetes binary executable by all so that kubernetes has permission to run it.

Fix permissions set by `node --kubernetes`

---

calico_containers/integrations/kubernetes/calico_kubernetes.py

Replace forward-slash character with underscore to make kubernetes labels valid in Felix ip-tables rules. Also removed replacement of `-` characteres since Kubernetes now accepts them as valid characters.
In Kubernetes, label names are passed to Felix which use them as rule-names (for human readability). However, Kubernetes accepts the `/` character, which Felix will error on. Therefore, we need to encode the `/` character. 
This PR is a temporary fix which converts `/` to `_`, but will result in collisions if an identical chain-name is passed in where the character is replaced. For example, if Kubernetes creates `custom/rule` and then creates `custom_rule`, there will be an IP Tables error in calico. (Opening a seperate issue to come up with a better encoding)

Convert felix-invalid "/" characters into "_" characters

---

Makefile
calico_containers/calico_ctl/node.py
calico_containers/integrations/kubernetes/calico_kubernetes.py
calico_containers/integrations/kubernetes/tests/kube_plugin_test.py
calico_containers/pycalico/tests/test_util.py
calico_containers/pycalico/util.py
calico_containers/tests/unit/calicoctl_test.py

Previous implementation of IP retrieval pings Google's DNS Server, this uses legacy RegEx formulas to  parse `ip addr` output

Network independent IP retrieval

---

calico_containers/pycalico/tests/test_util.py
calico_containers/pycalico/util.py

Python regex expression was grouping the subnet with the IP Address. Adjusted the parenthesis to confirm that a subnet is present but only return the IP address

Adjusted regex expression for IP Address

---

Makefile

Makefile accidently mentioned 'rkt' in a comment in the 'calico-kubernetes' section.

Fixed rkt typo in Makefile

---

build_calicoctl/Dockerfile

Our calicoctl binary depends on libc, and so we will bake in
a dependency on a newer distro by using something modern like
Ubuntu 14.04.
Switch to debian 7, which is new enough to meet our requirements,
while adding support for older distros.
(debian 7 comes with libc version 2.13-38+deb7u6).

Switch build container to debian

---

calico_containers/calico_ctl/bgp.py
calico_containers/calico_ctl/checksystem.py
calico_containers/calico_ctl/connectors.py
calico_containers/calico_ctl/container.py
calico_containers/calico_ctl/diags.py
calico_containers/calico_ctl/endpoint.py
calico_containers/calico_ctl/node.py
calico_containers/calico_ctl/pool.py
calico_containers/calico_ctl/profile.py
calico_containers/calico_ctl/status.py
calico_containers/calico_ctl/utils.py
calico_containers/calicoctl.py
calico_containers/nose.cfg
calico_containers/tests/unit/calicoctl_test.py

Fixes #361 
Unit tests are not yet fixed up - worth reviewing general strategy before spending time on UTs.
Despite the extensive changes, the actual change is logically small:
-  Add some checking of ETCD_AUTHORITY in the calicoctl code
-  Make client and docker_client methods rather than statically initialized connections (the fact that they were statically initialised made the checking of the authority rather skanky .. it too had to be done in static initialization code, and sys exiting from that doesn't feel right).   The bulk of the change was therefore to change client.method() to client().method().

Add start of day checking of etcd authority value.

---

build_calicoctl/Dockerfile
build_calicoctl/requirements.txt
docs/Building.md

Update build docs to include details about more make targets, and details on how to run fast and single STs, start up consul and etcd, installing pycalico library etc.

Build docs updates

---

docs/getting-started/AWS.md
docs/getting-started/DigitalOcean.md
docs/getting-started/GCE.md
docs/getting-started/VagrantCoreOS.md
docs/getting-started/VagrantUbuntu.md
docs/getting-started/default-networking/cloud-config/user-data-others
docs/getting-started/libnetwork/cloud-config/user-data-others
docs/getting-started/powerstrip/cloud-config/user-data-others

Replace instances of calico-01 and calico-02 when referencing hostnames with 172.17.8.101 and 172.17.8.102, respectively.

Updated doc hostname references to ip address equivalents

---

build_calicoctl/requirements.txt
calico_containers/calico_ctl/container.py
calico_containers/calico_ctl/node.py
calico_containers/requirements.txt
calico_containers/tests/unit/container_test.py
calico_containers/tests/unit/node_test.py

Calicoctl container commands now use the Namespace class to coincide with interface changes to namespace functions in libcalico.
Now use a regex for excluding the docker bridge interface when getting the machine's IP in calicoctl node.

Use Namespace class in calicoctl and regex for ip detect

---

calico_containers/calico_ctl/node.py
calico_containers/tests/unit/node_test.py

Fixes issue found [here](https://github.com/projectcalico/libcalico/issues/15)

Don't include cbr0 in IP autodetect

---

image/install.sh

Quick change to resolve issue #443 
Change basically uses an updated version of confd (in our own fork).  Shaun has tested the binary and testing indicates that it is working correctly.

Use projectcalico modified confd

---

image/base.sh

python-setuptools is old enough to have a bug that balks on python-etcd's version number (0.4.1+calico.1).  This works around by getting an up-to-date pip and setuptools.
Had to install ca-certificates manually, they were being pulled in as an indirect dependency and they're required to run curl.

Install a more recent version of pip/setuptools.

---

calico_containers/calico_ctl/node.py
calico_containers/tests/unit/node_test.py
node_filesystem/etc/rc.local

CALICO_NETWORKING defaults to true. When set to false, bird and confd are disabled.
The reason for the name change is to avoid confusion in the plugins. In the Kubernetes plugin we use an environment variable called CALICO_POLICY that indicates when the user wants to specify policy for pods. There should be a clear distinction between this environment variable and the calicoctl environment variable that disables bird.

Change env var POLICY_ONLY_CALICO -> CALICO_NETWORKING

---

docs/kubernetes/KubernetesIntegration.md

The docs for the KUBE_API_ROOT were unclear; they did not specify that the transport (http/https) must be specified to construct a valid URI. The example of the default value was also incorrect.
Fix this by giving a correct example of the default value.
FIXES: https://github.com/projectcalico/calico-kubernetes/issues/44

Fix documentation for KUBE_API_ROOT env variable

---

docs/kubernetes/KubernetesPolicy.md

In [`calico-kubernetes#50`](https://github.com/projectcalico/calico-kubernetes/issues/50), it was found that a few vital iptables proxy fixes went in after the initial PR.

Change Kubernetes commit sha for iptables proxy.

---

build_calicoctl/Dockerfile
build_calicoctl/requirements.txt

- Remove etcd (and curl since it was only needed to install etcd)
- Remove outdated comments
- Remove old requirements

Clean up build and UT container

---

Makefile
calico_containers/calico_ctl/checksystem.py
calico_containers/calico_ctl/node.py
calico_containers/calico_ctl/utils.py
calico_containers/tests/st/test_checksystem.py
calico_containers/tests/unit/checksystem_test.py
calico_containers/tests/unit/node_test.py
docs/getting-started/default-networking/EnvironmentSetup.md
docs/getting-started/default-networking/cloud-config/user-data-first
docs/getting-started/default-networking/cloud-config/user-data-others
docs/getting-started/default-networking/vagrant-ubuntu/Vagrantfile
docs/getting-started/libnetwork/EnvironmentSetup.md
docs/getting-started/libnetwork/cloud-config/user-data-first
docs/getting-started/libnetwork/cloud-config/user-data-others
docs/getting-started/libnetwork/vagrant-ubuntu/Vagrantfile
docs/getting-started/powerstrip/CalicoSwarm.md
docs/getting-started/powerstrip/EnvironmentSetup.md
docs/getting-started/powerstrip/cloud-config/user-data-first
docs/getting-started/powerstrip/cloud-config/user-data-others
docs/getting-started/powerstrip/vagrant-ubuntu/Vagrantfile

+ Fix #539
+ Remove all references to the --fix flag in guides
+ Remove checksystem calls in startup scripts
+ Make module checks more reliable

Deprecate `--fix` flag of `calicoctl checksystem`

---

docs/kubernetes/KubernetesIntegration.md

Document the env variable added in https://github.com/projectcalico/calico-kubernetes/pull/69.

Add documentation for KUBE_AUTH_TOKEN env variable

---

calico_containers/calico_ctl/endpoint.py
calico_containers/tests/unit/endpoint_test.py

When no profile is specified, output of the commands is unclear.  Add specific output for these cases to make it clear what action is being taken.

Improve output for endpoint profile commands

---

calico_containers/calico_ctl/container.py
calico_containers/tests/unit/container_test.py

Add call to new libcalico functionality merged in [#41 - increment metric of default routes to preserve networking before calico](https://github.com/projectcalico/libcalico/pull/41) 
This fixes #447

increment metric of default route when adding new default route

---

calico_node/build.sh

Reverts [60717cc3](https://github.com/projectcalico/calico-docker/commit/60717cc36a56392968cf1f8b92af102f6cbc36d4) since [#866](https://github.com/projectcalico/calico/pull/866) has been merged to master.
The `iptables-protocol-number` branch was deleted, so builds are broken until this PR is accepted!

Fix version of felix. Master version now has fix we need

---

calico_containers/calico_ctl/checksystem.py
calico_containers/calico_ctl/node.py
calico_containers/calico_ctl/status.py
calico_containers/tests/unit/node_test.py
docs/calicoctl/node.md

Base implementation to fix #564 . Adds the `--runtime` option with possible values of `docker` or `none`. This PR also patches some bugs encountered by `checksystem` and `status` which both assume a connection to the docker-daemon is available. 
Additional design is needed to provide more robust checksystem and status for dockerless systems, but I propose we raise separate issues in calico-docker to address improving these.

Run `calicoctl node` without launching docker

---

calico_containers/calico_ctl/node.py

This minimizes downtime during upgrade

Pull docker image before removing old container

---

calico_containers/tests/st/no_orchestrator/test_add_autoassigned_ip.py
calico_containers/tests/st/no_orchestrator/test_mainline_single_host.py
calico_containers/tests/st/test_base.py
calico_containers/tests/st/utils/docker_host.py
calico_containers/tests/st/utils/utils.py
calico_containers/tests/st/utils/workload.py
calico_node/build.sh

It doesn't work Docker-in-Docker - that requires Docker to do some IPv6 which requires additional config.
This works as long as an interface on the host has an autoconfigured link local address.

Add a simple IPv6 mainline test

---

Makefile
build_calicoctl/requirements.txt
calico_containers/tests/st/utils/docker_host.py
calico_containers/tests/st/utils/utils.py
calico_containers/tests/st/utils/workload.py
calico_node/build.sh
calico_test/Dockerfile
calico_test/requirements.txt

Create a container for running the STs.
- This container can be used as a way of sharing the ST framework code to libnetwork-plugin
- It reduces the requirements for running the STs - just `make st` on any host with a docker daemon.

Run STs in a container

---

docs/getting-started/libnetwork/CalicoSwarm.md

Fix two minor typos in the new Docker Swarm guide

Fix typos in Docker Swarm guide

---

Makefile

So I think including localhost in advertise client urls is not actually correct - although in our STs there won't be any side effect of it.
Also it's good to close down the available IPs clients can access the server with.
With this change, it is possible to connect using local host still.
As per etcd docs:
> etcd listens on listen-client-urls to accept client traffic. etcd member advertises the URLs specified in advertise-client-urls to other members, proxies, clients. Please make sure the advertise-client-urls are reachable from intended clients. A common mistake is setting advertise-client-urls to localhost or leave it as default when you want the remote clients to reach etcd.

Update etcd parms to limit allowable IPs

---

calicoctl/calico_ctl/utils.py

This change allows messages from print_paragraph to be directed to (for example) sys.stderr, which is useful for things like error messages.

Tweak print_paragraph to support a file parameter

---

calicoctl/calico_ctl/container.py
calicoctl/tests/unit/container_test.py
calicoctl/tests/unit/utils_test.py

may fix [this](https://github.com/projectcalico/libcalico/issues/68)
when comparing two IPPools, values should be specified, if create one IPPool, `masquerade`, `ipip`, `ipam` may not be the same as stored in etcd.

pool should always come from client

---

calicoctl/calico_ctl/__init__.py
calicoctl/calico_ctl/node.py
calicoctl/tests/unit/node_test.py
docs/RepoStructure.md
docs/calicoctl/node.md
docs/kubernetes/AWSIntegration.md
docs/kubernetes/KubernetesIntegration.md

Remove them from the calicoctl node command.
Removes install_binary too, the UTs and cleans up docs.

Remove the --kubernetes and --rkt commands

---

calicoctl/Dockerfile
calicoctl/calico_ctl/checksystem.py
calicoctl/calico_ctl/node.py
calicoctl/calico_ctl/utils.py
calicoctl/tests/unit/node_test.py

Add dockerfile and better support in calicoctl node for ignoring things it can't do.
Fixes #309

Support calico/ctl being run inside a container

---

docs/ExposePortsToInternet.md
docs/calico-with-docker/docker-network-plugin/README.md
docs/calico-with-docker/without-docker-networking/README.md

I've added a working example on how to expose a container port to the Host-Interface / Internet. this closes #726

add documentation for exposing conatiner ports. closes #726

---

docs/calico-with-docker/AWS.md
docs/calico-with-docker/GCE.md
docs/calico-with-docker/docker-network-plugin/cloud-config/user-data-first
docs/calico-with-docker/docker-network-plugin/cloud-config/user-data-others
docs/calico-with-docker/docker-network-plugin/vagrant-coreos/Vagrantfile
docs/calico-with-docker/docker-network-plugin/vagrant-ubuntu/Vagrantfile
docs/calico-with-docker/without-docker-networking/vagrant-coreos/Vagrantfile
docs/calico-with-docker/without-docker-networking/vagrant-ubuntu/Vagrantfile

Removed unnecessary cloud-config that installed docker 1.9 on CoreOS vagrant machines. Alpha CoreOS machines build come with docker 1.10.1 by default.  Modified Ubuntu vagrant docker binaries to be 1.10.1 also.
Fixes #837 
This change also fixes the bug where the docker images were not being pulled during the vagrant install (since there were two different docker binaries on the machine, the incorrect binary was pulling the images).
Fixes #838

Vagrant installs use Docker 1.10.1

---

docs/cni/kubernetes/AnnotationPolicy.md
docs/cni/kubernetes/NetworkPolicy.md
docs/cni/kubernetes/README.md
docs/cni/kubernetes/VagrantCoreOS.md
docs/cni/kubernetes/stars-demo/README.md
docs/cni/kubernetes/stars-demo/manifests/backend.yaml
docs/cni/kubernetes/stars-demo/manifests/client.yaml
docs/cni/kubernetes/stars-demo/manifests/frontend.yaml
docs/cni/kubernetes/stars-demo/manifests/management-ui.yaml
docs/cni/kubernetes/stars-demo/manifests/namespace.yaml
docs/cni/kubernetes/stars-demo/policies/allow-ui-client.yaml
docs/cni/kubernetes/stars-demo/policies/allow-ui.yaml
docs/cni/kubernetes/stars-demo/policies/backend-policy.yaml
docs/cni/kubernetes/stars-demo/policies/frontend-policy.yaml
docs/cni/kubernetes/vagrant-coreos/Vagrantfile
docs/cni/kubernetes/vagrant-coreos/cloud-config/master-config.yaml
docs/cni/kubernetes/vagrant-coreos/cloud-config/node-config.yaml
docs/cni/kubernetes/vagrant-coreos/guestbook.md
docs/cni/kubernetes/vagrant-coreos/manifests/calico-policy-services.yaml

Work in progress, just getting the pieces into the right place.
Still needs:

Documentation updates for Kubernetes v1alpha1 NetworkPolicy API.

---

release-scripts/do_release.py

simple-binary target doesn't work on release candidates, because it looks for libcalico.git@v0.13.0@master.  This is changed wrongly by the release scripts from libcalico.git@master: they try to do the right thing, but the specific libcalico@master regex falls further down the list than the generic libcalico one, so does nothing.

Move specific release version replacements above general ones and improve escaping

---

README.md

Fix coverage badge to use calico-containers, not calico-docker

---

calico_node/filesystem/startup.py
calico_test/tests/st/utils/utils.py

Add better IPv6 addr match check when starting node

---

Makefile

Couple of things going on here.
- Semaphore did a platform update on 4/26 which bumped docker to 1.11.0.
- The initial cause of ST failure was because our script was overwriting the install docker binary with a 1.10.1 binary. Due to the platform upgrade, this resulted in us downgrading docker. The 1.11 install comes with some flags which are unsupported in 1.10, so docker was failing to start after the downgrade. 
For now, this PR fixes builds by not installing the downloaded docker 1.10.0 on the host. This means we still download 1.10.0, which still gets uses it in the docker-in-docker builds. Therefore dind is now using a different version of docker than the host.
This opens subsequent work to update dind to 1.11.0. However, Its not as straightforward as it seems:
- Docker has updated …

Fix semaphore builds

---

calico_node/filesystem/startup.py
calico_test/tests/st/utils/docker_host.py
tests/st/no_orchestrator/test_mainline_single_host.py

Fixed bug where calicoctl node would fail to start up without being passed --ip, due to a failure to convert ipaddress to a string

Fixed calico start failure bug

---

calicoctl/calico_ctl/node.py
calicoctl/tests/unit/node_test.py

Fixes #920 
When the node fails due to some unknown error to `calicoctl`, `calicoctl` still exits with status 0.
Easily reproducable scenario is starting the calico node, changing hostname, then restarting the calico node.  `calicoctl` will show that the container did not start, but status is still 0.
This change ensures we are setting a clean status if we are expecting to shut down the container, otherwise exit with status 1.

Exit with status 1 when node container quits with bad status

---

Makefile
calico_test/Dockerfile
calico_test/tests/st/utils/docker_host.py

Update calico/containers to adhere to changes in [#1](https://github.com/projectcalico/dind/pull/1) whereby we no longer volume mount docker in from the host, but the new calico/dind which is built from the official dind image

Change dind from volume mount to official dind image

---

docs/calico-with-docker/docker-network-plugin/vagrant-ubuntu/Vagrantfile
docs/calico-with-docker/without-docker-networking/vagrant-ubuntu/Vagrantfile

Docker was failing to start when running the ubunutu vagrant demos because a newer version of docker is now the default. We were pulling docker 1.10, but the config for docker 1.11 uses a new flag that 1.10 doesn't know about. Just use the latest 1.11.
Fixes #892

Remove line to get docker 1.10 in ubuntu vagrants, 1.11 now default

---

calicoctl/calico_ctl/profile.py
calicoctl/tests/unit/profile_test.py

(Instead of validate_ports.  validate_port_spec validates the port
specifications that can be specified on the calicoctl command line. This
is different from validate_ports, which validates the port values that
can occur in the etcd data model.)

Use new validate_port_spec to validate port spec

---

calicoctl/tests/unit/profile_test.py

Since we've increased the range of valid ICMP types to include 255 in [libcalico#117](https://github.com/projectcalico/libcalico/pull/117).

Bumped ICMP validation test to use 256

---

docs/mesos/ManualInstallCalicoDockerContainerizer.md

We have had at least two issues where users missed the link to set the `cluster-store` parameter of the Docker daemon when using the Docker containerizer.
This change provides a small amount of duplication between the docker containerizer setup and the libnetwork docs, but it is worth it to provide a more streamlined experience with less errors.

Add doc section in Docker containerizer install to set cluster-store

---

docs/Building.md

It's about building from master so doesn't need a version header

Remove version header from building.md

---

calico_node/Dockerfile
calico_node/build.sh

This PR temporarily fixes the build by pinning the alpine image calico-node is built from to 3.3. 
See #1040 for more information on what may be causing failures.

Pinned alpine to fix setuptools issue.

---

docs/cni/kubernetes/KubernetesIntegration.md

Updated docs/cni/kubernetes/KubernetesIntegration.md to reference the
policy-controller.yaml file from the master branch rather than the
v0.2.0 tag because the latter has an outdated name for the policy
controller image.
Fixes #1052

Fix reference to policy-controller.yaml

---

docs/cni/kubernetes/stars-demo/README.md

The identification of step 4 was missing.  The step was there, but it
was not called out as a distinct step.

Identified step 4 in the stars demo

---

docs/cni/kubernetes/manifests/skydns.yaml
docs/cni/kubernetes/stars-demo/manifests/backend.yaml
docs/cni/kubernetes/stars-demo/manifests/client.yaml
docs/cni/kubernetes/stars-demo/manifests/frontend.yaml
docs/cni/kubernetes/stars-demo/manifests/management-ui.yaml
docs/cni/kubernetes/vagrant-coreos/Vagrantfile

The DNS manifest is used across the AWS, GCE, and Vagrant demos.  I've also checked that the stars demo works on each.
- Updates to latest kubedns
- Updates stars demo manifests to use correct domain names.
- Updates to use `calico/` versions of the stars Docker images rather than `caseydavenport/`

Update stars demo files and kubedns

---

calico_node/filesystem/startup.py

Fixes issue #1084 
I still need to test that this works for the DaemonSet use-case in the issue.

calico/node: default to socket.gethostname()

---

docs/cni/kubernetes/AWS.md

I think is good to reference OS X binary as well.
https://coreos.com/kubernetes/docs/latest/configure-kubectl.html#download-the-kubectl-executable

added link to OS X kubelet binary

---

calicoctl/calico_ctl/node.py
calicoctl/tests/unit/node_test.py

Fixes #1046 
Both Felix and libcalico accept CA being specified without the Key and Cert files.

CA can be specified separately

---

docs/calico-with-docker/docker-network-plugin/ManualSetup.md

Been seeing a lot of people miss this recently, so I've tried to make it a bit clearer that it probably does apply to the reader.

Make it clearer that libnetwork users must set --cluster-store

---

docs/mesos/vagrant-centos/units/docker.service.d/docker.conf

Fixed the docker systemd dropin as v1.12.0 of docker doesn't need fd:// in centos (apparently).
A better fix would be to change this so instead of using a systemd dropin, we set `daemon.json`...

Fix calico-mesos-docker demo

---

docs/cni/kubernetes/vagrant-coreos/Vagrantfile

The lack of localhost in /etc/hosts caused problems with kubectl
Fixes #1045

Provisioning /etc/hosts with localhost

---

calicoctl/calico_ctl/checksystem.py

In the case of an etcd connection failure, the error message that might help the user in diagnosing the problem is being swallowed.

Show etcd connection failure error message

---

calico_node/filesystem/etc/service/felix/run

Setting `-e HOSTNAME` on the calico-container did not update the hostname
Felix receives, which leads to surprise breakages (blackhole routes work, but
interface routes don't).
Closes #1105
Note: this is untested just yet. I'm wondering if adding automated container integration tests is possible?

Map HOSTNAME to FELIX_FELIXHOSTNAME in calico-node.

---

calico_node/build.sh

4 Days ago, runit was moved from `testing` to `community`: https://patchwork.alpinelinux.org/patch/2333/
This broke our builds for `calico/node`.

Get runit from community rather than testing

---

docs/calico-with-docker/docker-network-plugin/IPv6.md

Thanks for an already good examples and wiki. 
During trying out docker with calico IPv6 examples, I found few options missing in docker and calicoctl commands. Proposing minor modifications to take care of IPv6 case. I have tested this on my local setup. Changes seem minor and straightforward to me. 
Let me know in case I can help clarify the changes even further.
Thanks
Ketan

Minor Update to documentation.

---

docs/calico-with-docker/VagrantUbuntu.md
docs/calico-with-docker/docker-network-plugin/vagrant-ubuntu/Vagrantfile

Technology has moved on since Ubuntu 14.04 so that more and more people want to test Calico on Ubuntu 16.04.
Note, this Vagrantfile uses the `bento/ubuntu-16.04` box since the `ubuntu/xenial64` box is unusable unless it is customised. The Bento vagrant boxes are officially recommended by Hashicorp.
[https://www.vagrantup.com/docs/boxes.html](https://www.vagrantup.com/docs/boxes.html).

Adding Ubuntu 16.04 vagrant box

---

docs/cni/kubernetes/vagrant-coreos/cloud-config/master-config.yaml
docs/cni/kubernetes/vagrant-coreos/cloud-config/node-config.yaml

While setting up the cluster I had some download timeout or break in process and had to redownload all the files from storage.googleapis.com by hand.
This patch would save time and check if files have been downloaded completely.

Add -c flag to wget to continue downloading

---

docs/calico-with-docker/docker-network-plugin/vagrant-coreos/Vagrantfile
docs/calico-with-docker/docker-network-plugin/vagrant-ubuntu/Vagrantfile
docs/calico-with-docker/without-docker-networking/vagrant-coreos/Vagrantfile
docs/calico-with-docker/without-docker-networking/vagrant-ubuntu/Vagrantfile
docs/cni/kubernetes/vagrant-coreos/Vagrantfile
docs/cni/rkt/README.md
docs/cni/rkt/Vagrantfile

These were changes necessary to pass manual testing for the release.
Reference to coreos release.  Coreos alpha and stable are quite near in time, but the stable release works with Calico and will provide a better customer experience.
https://coreos.com/releases/

adjustments to improve the tutorial experience

---

docs/calico-with-docker/docker-network-plugin/IPv6.md

eth1 -> enp0s8
```bash
vagrant@calico-02:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:00:6c:4c:db
inet addr:172.18.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
UP BROADCAST MULTICAST  MTU:1500  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
enp0s3    Link encap:Ethernet  HWaddr 08:00:27:ee:32:98
inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
inet6 addr: fe80::a00:27ff:feee:3298/64 Scope:Link
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
RX packets:69366 errors:0 dropped:0 overruns:0 frame:0
TX packets:13934 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:95342352 (95.3 MB)  TX bytes:1022996 (1.0 MB)
**enp0s8** …
```

change default eth to match the latest Ubuntu vagrant setup

---

docs/cni/kubernetes/InstallAddons.md
docs/cni/kubernetes/manifests/README.md
docs/cni/kubernetes/manifests/calico-configmap.yaml
docs/cni/kubernetes/manifests/calico-hosted.yaml

This adds some documentation for the self-hosted work.
Relies on a new release of the CNI plugin which includes https://github.com/projectcalico/calico-cni/pull/177

Update manifests README to discuss self-hosted.

---

docs/cni/kubernetes/manifests/kubeadm/README.md
docs/cni/kubernetes/manifests/kubeadm/calico.yaml

Adds a sub-directory to the self-hosted manifests section which includes a kubeadm specific self-hosted install manifest.
This manfiest includes a simple etcd deployment as well, and configure Calico in `ipip` mode.

Kubeadm manifest

---

calico_node/Dockerfile
calico_node/filesystem/etc/rc.local
calico_node/filesystem/etc/service/available/libnetwork/log/run
calico_node/filesystem/etc/service/available/libnetwork/run
calicoctl/calico_ctl/node.py
calicoctl/tests/unit/node_test.py

- The new behavior is if calico/node is started with `calicoctl` and `--libnetwork` flag is passed then instead of running libnetwork-plugin in a separate container, we run it inside calico/node container.
- if calico/node is not started with `calicoctl` (like in case of k8s or manually starting the container), libnetwork can be enabled by passing an env var `CALICO_LIBNETWORK_ENABLED`, which is `false` by default and doesn't run libnetwork unless it's set to `true`

Libnetwork plugin bundled in calico/node container

---

Makefile

{} notation is a bashism.
make semaphore should still work on systems without /bin/bash.

Fix deletion of unwanted files on Semaphore to free up disk space

---

Makefile

We need to have an ability to provide custom URLs for calico
binaries to be downloaded from.
This patch allows to redefine the below variables:
CONFD_URL
BIRD_URL
BIRD6_URL
BIRDCL_URL

Allow to provide custom URL path for calico binaries

---

tests/st/test_checksystem.py
tests/st/test_diags.py
tests/st/test_endpoint.py
tests/st/test_ipip.py
tests/st/test_node.py
tests/st/test_pool.py
tests/st/test_profile.py
tests/st/test_status.py

Fixes import resolution for PyCharm (and it's best-practice to use absolute imports anyway in order to avoid any confusion with varying PYTHONPATHs).

Adjust ST imports to use absolute imports.

---

Makefile
calico_node/Dockerfile

Make building calico/node more friendly to CI.
Since calico/node image build process hardly depends on two pip
repositories (from git):
* libcalico
* libnetwork-plugin
we need to have an ability to test pull-requests/patches to the
above repos against calico-containers before merge. This patch
doesn't break the default behaviour (installing from github repos),
but allows us to customize pip repositories path.
Changes:
* Add ARG parameters to calico/node Dockerfile with the defaults:
ARG LIBCALICO_REPO="https://github.com/projectcalico/libcalico.git"
ARG LIBCALICO_VER="master"
ARG LIBNETWORK_REPO="https://github.com/projectcalico/libnetwork-plugin.git"
ARG LIBNETWORK_VER="master"
* COPY share dir `node_share` inside container to `/tmp/node_share`
Since docker build doesn't support mounting …

Allow to customize pip repos during node image build

---

release-scripts/do_release.py
release-scripts/utils.py

Update release scripts to account for the fact that:
- `calico/node` doesn't use `build.sh` anymore
- `projectcalico/calico` was renamed to `projectcalico/felix`

Fix release scripts

---

calicoctl/calicoctl.go
calicoctl/commands/apply.go
calicoctl/commands/create.go
calicoctl/commands/delete.go
calicoctl/commands/get.go
calicoctl/commands/ipam.go
calicoctl/commands/ipam/release.go
calicoctl/commands/ipam/show.go
calicoctl/commands/node.go
calicoctl/commands/node/checksystem.go
calicoctl/commands/node/diags.go
calicoctl/commands/node/status.go
calicoctl/commands/replace.go
calicoctl/commands/version.go

- handle errors locally instead of bubbling them up
- Print useful message when an invalid command is passed
- return proper exit codes (0 - success, 1 - failure/partial success)
- fix a bug where Felix SIG command wasn't getting executed
- some code tidy-up
fixes [#155](https://github.com/projectcalico/libcalico-go/issues/155)

error reporting + minor bugfixes

---

calicoctl/calicoctl.go
calicoctl/commands/apply.go
calicoctl/commands/config.go
calicoctl/commands/constants/help.go
calicoctl/commands/create.go
calicoctl/commands/delete.go
calicoctl/commands/get.go
calicoctl/commands/ipam.go
calicoctl/commands/ipam/release.go
calicoctl/commands/ipam/show.go
calicoctl/commands/node.go
calicoctl/commands/replace.go
calicoctl/commands/resources.go
calicoctl/commands/version.go
calicoctl/resourcemgr/node.go
glide.lock
test/host.yaml

This PR adds:
-  Node as a resource
-  System wide configuration options (and low level node configuration options).
It's possible that we'll make config a "resource" as well and that some of the node-specific config options could move into the node resource - but I think that can be done later with pretty minor deprecation and phase out.
I've also gone through the various command line helps and fixed the width at 79 characters because it was too long and uneven.  Should make our docs nicer once I cut and paste it into our docs.

Add config commands and node as a resource

---

Makefile

rc3 doesn't work with non-latest docker.

Move to latest libnetwork plugin rc4

---

calico_node/Dockerfile

should fix this issue with CoreOS:
```bash
core@calico-01 ~ $ docker run --net net1 --name workload-A -tid busybox
452d349d5df743701a337f86bc43e82668c27adede608d2cd502a7312ce8e02e
docker: Error response from daemon: failed to create endpoint workload-A on network net1: NetworkDriver.CreateEndpoint: {"Err":"Network 06efe5384c698245a8290c82353763eac06dc3ec6548c3a3d9ab275ef04adac0 inspection error: Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)"}
null.
```
```
core@calico-01 ~/calico-containers $ docker version
Client:
Version:      1.10.3
API version:  1.22
Go version:   go1.5.4
Git commit:   1f8f545
Built:
OS/Arch:      linux/amd64
Server:
Version:      1.10.3
API version:  1.22
Go version:   go1.5.4
Git commit:   1f8f545
Built: …
```

Docker API version for libnetwork

---

tests/st/test_profile.py

Reduce the number of tests that we run in calico-containers

Only run the tag related test

---

calico_node/Dockerfile

I think this should be all that's needed but it could do with a retest from @matthewdupre.
Fixes #1276 
Fixes https://github.com/projectcalico/felix/issues/1164

Keep CA store after build.  Required by golang felix for usage reporting

---

Makefile
calicoctl/resourcemgr/node.go

Fixes part of #1271 (but doesn't fix the displaying default ASN when ASN is not specified)
This also fixes the Makefile not rebuilding after changing calicoctl files.

Don't display nil when viewing node resources with the --wide option

---

Dockerfile.calicoctl

Add 'libltdl' library into 'calico/ctl' docker image

---

Makefile
calico_node/Dockerfile

check related commit: 7d0f4abad31e8e3edc24915aa3efcc546f585345

libcalico is no longer requered for node image

---

calicoctl/calicoctl.go

Closes: #1302 
Change-Id: If77775598469afc15cbafda79dc1c18c5aeeabbf

calicoctl: do exit(1) if command not found

---

calicoctl/commands/resources.go

Fixes #1308
Two things to note:
-  This will need documenting - probably just in the resources description sections (and perhaps a mention in our usage guides) ... i'm treating this as low priority for now.
-  This does not affect the reading/writing of YAMl files - the exact resource name is required for that.  Does k8s allow for alternate names in the YAML for the "kind" - if so we probably will want to have another issue - or just reject this PR (since I'll implement it in a different way - but deffo not in time for 2.0.0)

Add a selection of resource aliases

---

glide.lock
glide.yaml
test-data/all.yaml
test-data/policy-icmp-bad.yaml
test-data/policy.yaml
test-data/test4.yaml
tests/st/test_calicoctl.py
tests/st/test_profile.py

In particular this gets:
-  Profile tags moved to Metadata
-  Updated IP pool and Node deletion to remove associated IPAM data

Use latest libcalico-go

---

calico_node/startup.py

I currently have some devices with the device name matching `dummy*` that I do not want automatically detected. I have a hard time believing someone else would want such a device detected either.

do not detect IP addresses on dummy* devices

---

Makefile

By default (HTTP) Fail silently (no output at all) on server errors.
This is mostly done to better enable scripts etc to better
deal with failed attempts.
So we must fail if some resources are unavailable

curl should fail if smth is missing to download

---

calicoctl/commands/apply.go
calicoctl/commands/create.go
calicoctl/commands/delete.go
calicoctl/commands/get.go
calicoctl/commands/printer.go
calicoctl/commands/replace.go
calicoctl/commands/resources.go
calicoctl/resourcemgr/resourcemgr.go
glide.lock
glide.yaml
test-data/policy-bad.yaml
test-data/policy-invalid-field.yaml
tests/st/bgp/test_global_config.py
tests/st/calicoctl/test_crud.py

Fixes https://github.com/projectcalico/libcalico-go/issues/230
Fixes https://github.com/projectcalico/libcalico-go/issues/248
This PR relies on forks of three other libraries, these forks provide improved error details, swap Float32 with Float64 support, strict validation of unexpected fields.   Please also see the following PRs:
https://github.com/projectcalico/go-yaml/pull/1
https://github.com/projectcalico/go-yaml-wrapper/pull/1

Add improved error messages and use strict unmarshaling of data

---

calico_node/startup.py

In some setups, it may be necessary to have peer using different ASNs (for
example when using unique ASN per rack). When the Calico node container starts,
the preconfigured ASN is overwritten and the node is no longer able to peer. By
providing a new environment variable USE_HOST_AS we are able to use the
preconfigured value and survive container restarts.
This is particularly important when using a DaemonSet to deploy the nodes to all
hosts.

add flag to use predefined host ASN

---

Makefile

Accidentally removed in this comment (cut error .... when it should have been a copy)  
https://github.com/projectcalico/calico-containers/commit/fe16ac2e49cd15ba32a2bd5393a6c6c8127abb52

reinstate directory (accidentally removed)

---

Makefile

Use a single version, and the latest so we can spot problems with etcd
updates.

Makefile: Use latest etcd (in three places) for tests

---

calicoctl/commands/node/run.go

Spotted error on CoreOS.  Funning calicoctl node run errored and exited, but the calico/node container was running successfully.
Turns out that on the Vagrant CoreOS system, the version of Docker does not allow the `--follow` flag to appear after the container name in the `docker logs` command.
Just need to swap it round in the command.

Swap parm order round for docker logs command in calicoctl node run

---

calico_node/Dockerfile
calicoctl/Dockerfile.calicoctl
workload/Dockerfile

Use a single alpine image, pinned to version 3.4 (the latest release)

Use a single alpine image across different Dockerfiles

---

Makefile
tests/st/policy/test_felix_gateway.py

Requires Felix after d457d0a2e6017cac7c9a19c5189a6a7d7faf8063 (currently golang-dp-driver branch).
@lwr20 Please can you take a look at this?  I based it on your in-progress STs so functions like `wipe_etc()` should probably be moved to a utility lib once our code is in the same repo.

Add test of Calico on a NAT gateway.

---

Makefile
Makefile.calico-node
Makefile.calicoctl

Looks as though the default node image was updated to use quay, but we weren't tagging our calico/node image as quay, nor tarring up the quay image for use with the STs.
Upshot of this is that the STs will be downloading quay.io/calico/node:latest each time we start calico node.  Explains why the STs were taking so damn long.  It might also explain why #1488 is working ... I think that will need to be rebased off this once it is in.

Tag quay latest after build

---

Makefile
Makefile.calico-node
Makefile.calicoctl
tests/st/utils/docker_host.py

After #1490 was merged you are always forced to tag calico/node and calico/ctl images with quay.io, even if you just build stuff locally and not going to upload it somewhere. That change also may confuse if you   upload calico images to your private registry instead of quay.io or docker hub.
I propose to revert changes from #1490 and add an ability of image name specifying for the system tests.

Remove quay.io tagging

---

calicoctl/Dockerfile.calicoctl

Command 'calicoctl node run' requires that Docker
client is available inside container and it needs
glibc.
Change-Id: I290c93b5b8dedf6a621e9ee846216ac2ae8d34f1

Build calico/ctl Docker image with glibc binaries

---

calico_node/startup/startup.go

Changing the query we use for WAIT_FOR_DATASTORE so that it's compatible with the k8s datastore driver.
Didn't work with a Profile because the k8s datastore driver doesn't support ProfileTagsKey, just ProfileKey, and the `lib/backend/compat` code translates requests for `ProfileKey` into `ProfileTagsKey`

Use FelixConfig in WAIT_FOR_DATASTORE

---

calico_node/filesystem/etc/rc.local

Delete the log directories in the "enabled" not "available" directories
Fixes #1519

calico/node: Fix DISABLE_FILE_LOGGING

---

calico_node/allocateipip/allocate_ipip_addr.go
calico_node/filesystem/etc/calico/confd/templates/tunl-ip.template
tests/st/calicoctl/test_ipip.py

Check if IPIP pools are disabled before assigning IP, and update tunl IP when pool is disabled

---

calico_node/filesystem/etc/rc.local
calico_node/filesystem/etc/service/available/confd/run

This one's a doozy.
There's a bug in etcd (3.1.0, 3.1.1, and 3.1.2) where [advertise-client-urls is always overwritten to be localhost:2379, even when it is manually set to something else](https://github.com/coreos/etcd/issues/7348). 
If I have a client programmed to connect to a remote etcd, and my client has "discovery" turned on, the etcd server will tell the client to reconnect via `localhost:2379`. If my client isn't on the same node as etcd, this will of course fail.
Currently, all other calico components besides confd (i.e. Felix, startup.go, calicoctl, and k8s-policy) do not connect with "discovery" on. They ignore the bad advertise url and have no issue reading and writing from etcd.
Confd, however, defaults to discovery mode. It will reconnect to localhost and fail repeatedly …

Turn off confd discovery

---

calico_node/filesystem/etc/calico/confd/templates/bird.cfg.mesh.template
calico_node/filesystem/etc/calico/confd/templates/bird6.cfg.mesh.template

Check that the IPv4 address key is present before trying to get the value.
It's a very "mainline" change in the template so it's getting good coverage in the STs, but there is no ST to test the actual issue that led to us wanting this fix (since that would require jimmying around in etcd).

Update templates to handle missing node BGP IP

---

Makefile.calico-node
calico_node/filesystem/etc/rc.local
calico_node/filesystem/etc/service/available/confd/run
calico_node/startup/startup.go
glide.lock
glide.yaml

This PR coincides with a PR for libcalico-go and projectcalico/confd here:
projectcalico/libcalico-go#354
projectcalico/confd#4
With those two PRs this will allow calico/node to operate with the Kubernetes Datastore Driver and Bird BGP routing enabled in node-mesh mode.
- Updated the shell scripts to detect if running KDD and launch confd accordingly
- startup.go modifications to push all of the required info to KDD

Updating startup.go for Kubernetes Datastore Driver with bird

---

Makefile.calico-node

From https://github.com/projectcalico/bird/releases/tag/v0.3.0 :
Merge Calico's BIRD patches with the upstream BIRD 1.6.3 code.
Calico's BIRD fork was previously based on BIRD 1.5.0, so this merge
brings in the following upstream BIRD changes (notes from
http://bird.network.cz/?o_news).
- 1.6.0 (29.4.2016) RIP protocol redesigned, new protocol babel, BGP
multipath added.
- 1.6.1 (22.9.2016) IPv6 ECMP support, several improvements in filters,
kernel protocol, babel, memory leak in BGP multipath fixed.
- 1.6.2 (29.9.2016) Fixed serious bug of the previous version.
- 1.6.3 (22.12.2016) Large BGP communities, new authentication in BFD,
RIP and OSPF.
Of particular interest for Calico is the BGP multipath and ECMP support
- see the documentation for merge paths at …

Use BIRD v0.3.0

---

Makefile.calico-node

Rev Felix to this version to give it more exposure: https://github.com/projectcalico/felix/releases/tag/2.2.0-pre1

Rev Felix to 2.2.0-pre1.

---

calico_node/filesystem/etc/calico/felix.cfg

Should avoid this warning emitted at startup:
```
2017-04-07 08:33:33.120 [ERROR][40] logutils.go 147: Failed to connect to syslog error=Unix syslog delivery error level="WARNING"
```

Disable Felix syslog logging, which doesn't work inside calico/node.

---

Makefile

We really shouldn't need >15GB to run our tests, but we do...

Makefile: Free even more diskspace on semaphore

---

calicoctl/commands/node/run.go

Trace out additional diags if `calicoctl node run` fails.

Trace out docker logs if calicoctl node run fails

---

calicoctl/commands/get.go

Fixes #1610
Fixed missing newlines in `calicoctl get foo -o` options, this was making the output flow into the CLI prompt.

Fix for missing newlines in "get" errors

---

calico_node/Dockerfile

Better security to track latest

calico/node: Dockerfile, use latest alpine

---

Makefile.calico-node

To ensure that latest alpine release is used

calico/node: Makefile, always pull alpine

---

calicoctl/commands/node/run.go

Remove the following calico/node environment variables when running (or dry run of) calico/node:
- NO_DEFAULT_POOLS: only set when nopools is true
- IP[6]_AUTODETECTION_METHOD: calico/node defaults to
first-found, so only set when the method is not first-found
See issue: https://github.com/projectcalico/calicoctl/issues/1520
Testing: manual with enhanced calico/node debug logging

Elide redundant calico/node environment variables.

---

calicoctl/resourcemgr/resourcemgr.go
calicoctl/util/yaml/separator.go
calicoctl/util/yaml/separator_test.go
calicoctl/util/yaml/yaml_suite_test.go

Added the ability for calicoctl to iterate over multiple YAML documents from the same input 
Fixes https://github.com/projectcalico/libcalico-go/issues/47
- Ran/wrote unit tests
- Ran system tests
- Tested by creating multiple policies from the same YAML file locally

Added ability for calicoctl to read multiple yaml documents in the same file

---

calicoctl/commands/apply.go
calicoctl/commands/clientmgr/client.go
calicoctl/commands/config.go
calicoctl/commands/constants/help.go
calicoctl/commands/create.go
calicoctl/commands/delete.go
calicoctl/commands/get.go
calicoctl/commands/ipam/release.go
calicoctl/commands/ipam/show.go
calicoctl/commands/node/run.go
calicoctl/commands/replace.go

Print an error and exit when non-default config file is missing. Error only when the user specifies a non-default ("/etc/calico/calicoctl.cfg") config file via --config= option.
Issue: https://github.com/projectcalico/calicoctl/issues/1678
* Manually tested all commands with the following scenarios:
* Valid /etc/calico/calicoctl.cfg file
* Missing /etc/calico/calicoctl.cfg file
* Valid non-default config file (e.g. fun.yaml)
* Missing non-default config file

Report error and exit when non-default config file is missing.

---

glide.lock
glide.yaml

Rev libcalico-go to latest (to include KDD routing updates).

Update libcalico-go in glide to include kdd routing

---

calicoctl/commands/node/run.go

See issue: https://github.com/projectcalico/calicoctl/issues/1520
No longer set the following environment variables when they're set to libnetwork-plugin's default:
- CALICO_LIBNETWORK_CREATE_PROFILES (enabled by default in libnetwork-plugin)
- CALICO_LIBNETWORK_LABEL_ENDPOINTS (disabled by default in libnetwork-plugin)
- CALICO_LIBNETWORK_IFPREFIX ("cali" by default in libnetwork-plugin)
- Manually validated correct environment values based on appropriate calicoctl flags.
- Validated default values in libnetwork-plugin
- Ran basic docker sanity test to confirm functionality still works

Remove CALICO_LIBNETWORK* env variables when they're set to default values

---

calicoctl/commands/node/run.go

Felix now supports taking the iptables lock, which is file-based so it needs to be mapped into the container.

Map /run into the container for iptables lockfile.

---

Makefile
calicoctl/commands/version.go

As title says.
Also fixed build date in the Makefile so it is set properly.
```release-note
The calicoctl version command now includes the CalicoVersion and ClusterType as retrieved from the datastore.
```

Report version and cluster type from datastore in version command

---

Makefile
RELEASING.md

Doesn't looks like this is used anywhere anymore. 
```release-note
None required
```

Remove LIBCALICOGO_VER from Makefile

---

calicoctl/commands/node/status.go

Correct "node status" help typo (incudes->includes)
see issue: https://github.com/projectcalico/calicoctl/issues/1693
```release-note
None required
```

fix node status help typo

---

calicoctl/calicoctl.go
calicoctl/commands/apply.go
calicoctl/commands/clientmgr/client.go
calicoctl/commands/create.go
calicoctl/commands/delete.go
calicoctl/commands/get.go
calicoctl/commands/node/checksystem.go
calicoctl/commands/node/diags.go
calicoctl/commands/node/run.go
calicoctl/commands/node/status.go
calicoctl/commands/printer.go
calicoctl/commands/replace.go
calicoctl/commands/resources.go
calicoctl/resourcemgr/resourcemgr.go
glide.lock
glide.yaml

Updating the logrus import to use the new updated user name (which is lowercased).  This will prevent import errors with vendoring going forward.
Requires https://github.com/projectcalico/libcalico-go/pull/484
```release-note
None required
```

Update the import for logrus to use lowercasing

---

glide.lock
glide.yaml

update to libcalico-go v1.6.0
```release-note
None required
```

update to libcalico-go v1.6.0

---

calicoctl/commands/node/diags.go

Fixes #1690 
Fixes projectcalico/calico#810
With this change `calicoctl node diags` will pickup logs from hosted installs.  This will allow for easier and quicker debugging when a user sends us their debug logs with hosted installs.
There is also a small change to add some clarity when a command fails, as before it was simply saying `exit status 1` will now tell you what command failed to run. This will give the user a better idea of what failed to run in the diags.
I've tested this via the Calico vagrant demo and verified it works with and without Calico containers (obviously not writing any logs when there are no Calico containers present).
```release-note
`calicoctl node diags` will now gather logs from hosted Calico containers.
```

calicoctl node diags grab logs from hosted installs

---

glide.lock
glide.yaml

This PR pins glide to a libcalico-go that has support for manipulating Calico policies.
Tested by manually running through [Advanced Policy Demo](https://docs.projectcalico.org/v2.5/getting-started/kubernetes/tutorials/advanced-policy) in KDD mode.
```release-note
calicoctl now supports creating, updating, and deleting Calico policies when deployed using the Kubernetes datastore backend.
```

Pin to libcalico-go with KDD Calico Policy support

---

calicoctl/resourcemgr/policy.go
tests/st/calicoctl/test_crud.py

Prevent creating or manipulating kubernetes network policy using calicoctl.
```release-note
None required
```

Do not allow manipulating Network Policy resources using calicoctl

---

glide.lock
glide.yaml

Update the libcalico-go pin to v1.7.1
```release-note
None required
```

Update libcalico-go to v1.7.1

---

tests/st/calicoctl/test_crud.py

Add a couple of named-port CRUD tests for calicoctl.
```release-note
None required
```

add two named-port CRUD tests

---

calicoctl/commands/config.go
calicoctl/commands/printer.go

Removed redundant `return` statement and simplified `if` statement
```release-note
None required
```

Fixed small changes

---

calicoctl/resourcemgr/resourcemgr.go
calicoctl/util/yaml/separator.go
calicoctl/util/yaml/separator_test.go

This is a quick fix for #1722.  It simply increases the buffer size to allow a much larger document.
Fixes #1722
```release-note
None required
```

Increase document separator's maximum buffer size to 10MB.

---

glide.lock
glide.yaml
tests/st/calicoctl/test_crud.py

Pinning libcalico-go to the `v1.x-series` branch.  This is to resolve some issues we're seeing in the Calico Node `v2.x-series` STs.
```release-note
None required
```

Revving libcalico-go to v1.x-series

---

calicoctl/commands/get.go
calicoctl/commands/printer.go
calicoctl/resourcemgr/networkpolicy.go
calicoctl/resourcemgr/resourcemgr.go
calicoctl/resourcemgr/workloadendpoint.go

Print namespaces as the first column.
Only print namespace column if getting 'all-namespaces' or a specific namespace.
```release-note
None required
```

Change namespace output to more closely match K8s

---

calicoctl/commands/get.go
calicoctl/commands/node/run.go
calicoctl/resourcemgr/resourcemgr.go
glide.lock
glide.yaml
tests/st/calicoctl/test_crud.py
tests/st/utils/data.py
tests/st/utils/utils.py

Added the handling for metadata fields that are populated by the datastore so they should not be overwritten by any calicoctl operations. The fields that are the exception to this rule is `Labels` and `Annotations`.
```release-note
None required
```

Metadata handling for immutable fields

---

calicoctl/commands/get.go
calicoctl/commands/resources.go
tests/st/calicoctl/test_crud.py
tests/st/utils/data.py

Add the "export" option modeled after the K8s option. This will allow the calicoctl "get" output to be applied without needing modification.
```release-note
Added --export flag to the calicoctl get command to allow for resources to be applied across clusters strictly from the calicoctl output.
```

Add the export option in calicoctl to allow users to be able to apply calicoctl get output

---

Makefile
README.md

Restore the `st` dependency on the `test` target. The intent is to have a single target to run prior to pushing a commit.
```release-note
None required
```

re-add st dependency to test target

---

glide.lock
glide.yaml

Bump libcalico go v1.7.3
```release-note
None required
```

rev libcalico-go to v1.7.3

---

Makefile
calicoctl/Dockerfile.calicoctl
calicoctl/Dockerfile.calicoctl-ppc64le
calicoctl/Dockerfile.calicoctl.build-ppc64le

Signed-off-by: David Wilder <wilder@us.ibm.com>
Adding support for ppc64le.
I ran the following tests and saw no issues:
ARCH=ppc64le make semaphore  (on ppc64)
make semaphore   (on amd64)
ARCH=amd64 make semaphore  (on amd64)

Adding support for ppc64le builds.

---

tests/st/calicoctl/test_crud.py

noticed a duplicate test_method name which wasn't getting run. After making it unique, it was failing so I fixed that up.
```
[success] 6.68% tests.st.calicoctl.test_crud.TestCalicoctlCommands.test_namespaced_0: 5.0868s
[success] 6.34% tests.st.calicoctl.test_crud.InvalidData.test_invalid_profiles_rejected_5_bgpPeer_unrecognisedfield: 4.8252s
[success] 6.16% tests.st.calicoctl.test_crud.TestCalicoctlCommands.test_namespaced_1: 4.6874s
[success] 5.14% tests.st.calicoctl.test_crud.TestCalicoctlCommands.test_get: 3.9132s
[success] 3.93% tests.st.calicoctl.test_crud.InvalidData.test_invalid_profiles_rejected_6_hostEndpoint_invalidInterface: 2.9934s
[success] 3.59% tests.st.calicoctl.test_crud.TestCalicoctlCommands.test_clusterinfo: 2.7347s
[success] 3.42% …
```

rename test so it will get picked up and fix assertions

---

calicoctl/calicoctl.go
calicoctl/commands/convert.go
calicoctl/commands/v1resourceloader/v1resourceloader.go
glide.lock
glide.yaml
test-data/v1/bgppeer-node2.yaml
test-data/v1/multi-resource.yaml

example multi-resource manifest conversion:
Original:
```yaml
cat ../test-data/v1/multi-resource.yaml
- apiVersion: v1
kind: bgpPeer
metadata:
node: Node1
peerIP: aa:bb::ff
scope: node
spec:
asNumber: 64514
- apiVersion: v1
kind: bgpPeer
metadata:
node: Node2
peerIP: 1.2.3.4
scope: node
spec:
asNumber: 6455
---
apiVersion: v1
kind: bgpPeer
metadata:
scope: global
peerIP: 192.20.30.40
spec:
asNumber: 64567
---
- apiVersion: v1
kind: ipPool
metadata:
cidr: 192.168.0.0/16
spec:
ipip:
enabled: true
- apiVersion: v1
kind: ipPool
metadata:
cidr: 2001::00/120
spec:
```
Conversion command:
```bash
calicoctl convert -f ../test-data/v1/multi-resource.yaml -o yaml
```
```yaml
- apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
creationTimestamp: null
name: …
```

Add calicoctl convert command for manifest offline conversions

---

test-data/v1/migration/README.md
test-data/v1/migration/bgppeer.yaml
test-data/v1/migration/hostendpoint.yaml
test-data/v1/migration/ippool.yaml
test-data/v1/migration/node.yaml
test-data/v1/migration/policy.yaml
test-data/v1/migration/profile.yaml
test-data/v1/migration/workloadendpoint.yaml

These manifests along with the ones already present in `test-data/v1` should be used to test out the offline migration functionality.
```release-note
None required
```

Manifests for v1 to v3 migration testing

---

Makefile
tests/st/calicoctl/test_upgrade.py
tests/st/utils/utils.py
tests/st/utils/v1_data.py

Adds FV tests for the converter: `calicoctl convert`.
```
$ make st
<snipped out test run output>
----------------------------------------------------------------------
XML: /code/nosetests.xml
[success] 3.45% tests.st.calicoctl.test_upgrade.hep_tame('hep_tame', False): 2.6423s
[success] 3.44% tests.st.calicoctl.test_upgrade.policy_big('policy_big', False): 2.6295s
[success] 3.43% tests.st.calicoctl.test_upgrade.bgppeer_dotted_asn('bgppeer_dotted_asn', False): 2.6202s
[success] 3.21% tests.st.calicoctl.test_upgrade.node_long_name('node_long_name', False): 2.4550s
[success] 3.21% tests.st.calicoctl.test_upgrade.bgppeer_long_node_name('bgppeer_long_node_name', False): 2.4543s
[success] 3.13% tests.st.calicoctl.test_upgrade.profile_big('profile_big', False): 2.3951s
[success] 3.13% …
```

Add converter FV tests

---

tests/st/calicoctl/test_convert.py

This PR adds tests to run the new `convert` command and then `apply` the resulting manifest.  The manifests used are some existing (valid) ones and new ones that were created with all fields specifically to test the offline conversion and online conversion.

Add ST to run manifest convert tests

---

calicoctl/resourcemgr/resourcemgr.go
tests/st/calicoctl/test_crud.py

In cases where a resource version has been compacted in etcd and is then attempted to be updated, it gives the unclear error message `resource: etcdserver: mvcc: required revision has been compacted` instead of notifying the user that they are passing in an old resource version. This fixes the error message and makes it so updates are always done against the newest version of the resource.
```release-note
None required
```

Disallow any updates on old resource versions to fix etcd compaction errors

---

calicoctl/calicoctl.go

`docopts` provides an implicit `--version` flag even when you don't pass in a command.
However the output is terse and doesn't agree with the output from the `version` command. For example:
* `--version`: `calicoctl version v2.0.0-10-gec291442-dirty, build ec291442, CNX`
* `version` command:
```
Client Version:    v2.0.0-10-gec291442-dirty
Release:           CNX
Build date:        2018-02-22T23:33:12+0000
Git commit:        ec291442
Cluster Calico Version:  v3.0.1
Cluster CNX Version:     unknown
Cluster Type:            kubeadm,bgp,k8s
```
This PR disables the `--version` flag - just like kubectl, e.g.:
```
error: unknown flag: --version
```
```release-note
None required
```

disable --version flag (prefer the 'version' command)

---

glide.lock
glide.yaml
test-data/v1/policy.yaml
tests/st/calicoctl/test_crud.py
tests/st/utils/data.py

- Bumps libcalico-go to latest version
- fixes some sample policies that violated new icmp validation
```release-note
None required
```

Bump libcalico go

---

glide.lock
glide.yaml

Move up libcalico-go for PR: https://github.com/projectcalico/libcalico-go/pull/829

Update libcalico-go to f94d044d5357e7d8939fec43efc14124408cd2b9

---

calicoctl/resourcemgr/resourcemgr.go
tests/st/calicoctl/test_crud.py

~This PR fixes the issue where running an Apply against a resource where Create is not supported returns a "not found error". We now will return "operation not supported".~
~Implemented by changing error logic for `Apply` such that if the `Create` is Unsupported and `Update` is NotFound, return the Create's Unsupported error.~
~I needed to revert my original fix for this (#1831 ) since there are resources that you can Apply but not Create: Node resources in KDD mode.~
Added a special case for the "clusterinfo apply" so that we return `unsupported` error. This fixes an issue where running `apply` against a clusterinfo with name != default returns a `not found` error (since the `create` is unsupported and the `update` needs to run a `get` first).
I'm not happy about adding clusterinfo …

Handle unsupported applies

---

calicoctl/commands/node/diags.go

`exec.Command()` doesn't correctly handle escaped quotes. Consequently the `docker ps -a --filter "name=calico"` command fails and we're not correctly listing relevant pods to examine for the diag. The fix is to remove the escaped quotes from the invocation.
See https://stackoverflow.com/questions/26473674/double-quotes-escaping-in-golang-exec
Addresses issue: https://github.com/projectcalico/calicoctl/issues/1852
cherry-pick: https://github.com/projectcalico/calicoctl/pull/1853/commits/29bcb35b77062ea3c532f848e3eaf7a30d3b3c8d
```release-note
Fix invalid filter in "calicoctl node diags" command
```

fix up docker filter for name=calico

---

calicoctl/commands/node/status.go

We were panicking when we hit an error getting CLI args for a process. However, that included times when the process terminated between listing the processes and looking up the CLI args.
This PR handles that case more gracefully. 
```release-note
Fix calicoctl node status handling of terminated processes
```

Fix panic in node status when process is terminated

---

calicoctl/calicoctl.go

We already support 'calicoctl version', which prints information like
this:
Client Version:    v3.4.0-0.dev-15-g553bb080-dirty
Git commit:        553bb080
no etcd endpoints specified
However we don't support the standard 'calicoctl --version', and it
would be better if we did.  (Even our own Makefiles expect this; see
https://github.com/projectcalico/node/blob/master/Makefile#L459)
With this change, 'calicoctl --version' will print information likes
this:
calicoctl version v3.4.0-0.dev-15-g553bb080-dirty, build 553bb080
We could refactor more to make this output the same as 'calicoctl
version', but I think this is good enough as is and that the further
work isn't clearly justified.

Support calicoctl --version

---

Makefile

These flags prevent CI from building as it does not have TTY. Also, it does not need to be interactive.
```release-note
None required
```

Remove TTY and interactive flags from build

---

calicoctl/commands/version.go

Output is like this:
```
calicoctl v3.4.0-0.dev-18-g338531f8, build 338531f8
Run 'calicoctl version' to see cluster version information as well.
```

Improve 'calicoctl --version' output

---

calicoctl/commands/label.go
tests/st/calicoctl/test_crud.py

fix `calicoctl label` command panic on nil map dereference when resource has no labels.
Sorry for the bug imported in #1950. 
```release-note
None required
```

fix label command panic when resource has no label

---

calicoctl/calicoctl.go
tests/st/calicoctl/test_flags.py

Addresses #1910. This fix looks for the returning `err` and exits if present.
If the `err` is a `UserError`, we remind the user of the `--help` option.
I tested positive and negative tests and added some checks to the Python scripts.
```release-note
calicoctl will now return a non-zero exit code when passed an unknown flag
```

Catch and exit on bad command-line flags

---

Makefile

Clear `.go-pkg-cache` during a `make clean`.
```release-note
None required
```

clean out go-pkg-cache during

---

calicoctl/commands/argutils/args.go
calicoctl/commands/delete.go
calicoctl/commands/get.go
calicoctl/commands/resources.go
calicoctl/resourcemgr/resourcemgr.go
tests/st/calicoctl/test_crud.py
tests/st/utils/data.py
tests/st/utils/utils.py

On get/delete do not fail with the first failing resource. To be more
in line with kubectl, keep going, report success where appropriate
and report errors for failing resources. If there was any error,
calicoctl has non-zero exit status.
fixes OS-3934
fixes #1796 
```release-note
calicoctl get/delete per resource type can take multiple names
```

Allow delete/get to specify multiple names

---

calicoctl/commands/ipam/show.go

Do not return error code in ipam show if ip does not exist
```
DATASTORE_TYPE=kubernetes KUBECONFIG=~/.kube/config bin/calicoctl-linux-amd64 ipam show --ip=1.1.1.1
echo $?
1
```
is back to 
```
DATASTORE_TYPE=kubernetes KUBECONFIG=~/.kube/config bin/calicoctl-linux-amd64 ipam show --ip=1.1.1.1
echo $?
0
```
```release-note
None required
```

Fix regression in reporting errors in ipam show

---

calicoctl/commands/get.go

Missing new line when there is multiple errors in get
fixes 
```
tomas@tomas:~/go/src/github.com/projectcalico/calicoctl (tomas-ipam-show-fix-exit-status)$ DATASTORE_TYPE=kubernetes KUBECONFIG=~/.kube/config bin/calicoctl-linux-amd64 get policy x y z
resource does not exist: NetworkPolicy(default/default.x) with error: networkpolicies.crd.projectcalico.org "default.x" not foundresource does not exist: NetworkPolicy(default/default.y) with error: networkpolicies.crd.projectcalico.org "default.y" not foundresource does not exist: NetworkPolicy(default/default.z) with error: networkpolicies.crd.projectcalico.org "default.z" not found
```
as
```
tomas@tomas:~/go/src/github.com/projectcalico/calicoctl (tomas-fix-missing-new-lines)$ DATASTORE_TYPE=kubernetes KUBECONFIG=~/.kube/config …
```

Fixed missing new line in get errors

---

Makefile
calicoctl/commands/ipam.go
calicoctl/commands/ipam/show.go
tests/fv/ipam_test.go
tests/fv/utils/calicoctl.go

IPAM utilization reporting

---

calicoctl/commands/ipam/show.go
tests/fv/ipam_test.go

We were calculating `<large float64> - (<large float64> - <IPs in use>)`,
which gives 0 when `<IPs in use>` is small.  Fix that by removing that
calculation (which was unnecessary).
```release-note
None required
```

Fix showing IPS IN USE from a large pool as 0

---

calicoctl/resourcemgr/resourcemgr.go
calicoctl/resourcemgr/resourcemgr_test.go
tests/st/calicoctl/test_crud.py

Remove validation when unmarshalling a resource. The validation will be handled by lib calico, when calling create or update. Libcalico will also set the defaults for missing fields in the process of update/create.
Validation of resources needs to be done after setting the proper default values. For example, for VXLAN mode this should be Never rather than an empty string.
For example, when applying an ip pool policy with IPV6 CIDR and no VXLAN mode selected via calicoctl apply -f
```
---
kind: IPPool
apiVersion: projectcalico.org/v3
metadata:
name: ippool-2
spec:
cidr: 2002::/64
ipipMode: Never
natOutgoing: true
```
Calicoctl crashes with (VXLANMode other than 'Never' is not supported on an IPv6 IP pool)
```release-note
Set resource defaults before performing validation in calicoctl. …
```

Remove unmarshalling when creating a resource

---

calicoctl/commands/node/run.go

Support the `etcdDiscoverySrv`/`$ETCD_DISCOVERY_SRV` option added to the configuration in https://github.com/projectcalico/libcalico-go/pull/1086/
```release-note
None required
```

calicoctl node run: Plumb in $ETCD_DISCOVERY_SRV

---

calicoctl/commands/ipam/show.go
tests/st/calicoctl/test_crud.py
tests/st/utils/utils.py

Does not panic
Adds assert_output_not_contains in test infra
fixes OS-4514
Adds some testing about broken store configuration. However, those tests take ~10s to timeout and fail.
```release-note
None required
```

Fix crash in ipam when NewClient fails

---

calicoctl/resourcemgr/resourcemgr.go
calicoctl/resourcemgr/resourcemgr_test.go
tests/st/calicoctl/test_crud.py

Cherry pick of #2015 on release-v3.7.
#2015: Remove validation when unmarshalling a resource
```release-note
Set resource defaults before performing validation in calicoctl. Note: when creating multiple resources from a single file, calicoctl will now successfully create all valid resources up to the first invalid one before exiting with an error. (@asincu) 
```

Automated cherry pick of #2015: Remove validation when unmarshalling a resource

---

calicoctl/commands/node/run.go

Remove references to libnetwork, which is no longer part of v3.
Related to this PR for the /node project is https://github.com/projectcalico/node/pull/266
- Removed references to CALICO_LIBNETWORK in /node/run.go as Calico Libnetwork is no longer part of the node project.
- Tests have been run using `make test`
- No new tests have been added, nor was new code.
- Related, but not required: https://github.com/projectcalico/node/pull/266

Remove references to libnetwork, which is no longer part of calico/node

---

calicoctl/commands/ipam/show.go

Only say "not assigned" for ErrorResourceDoesNotExist errors

---

calicoctl/commands/apply.go
calicoctl/commands/create.go
calicoctl/commands/resources.go
tests/st/calicoctl/test_crud.py
tests/st/utils/data.py

This fixes `Partial success` messages being returned to the user when the command failed completely. E.g.:
```
$ calicoctl apply -f - <<EOF
> apiVersion: projectcalico.org/v3
> kind: BGPPeer
> metadata:
>   name: some.name
> spec:
>   node: rack1-host1
>   peerIP: oops
>   asNumber: 63400
> EOF
Partial success: applied the first 1 out of 1 'BGPPeer' resources:
Hit error: error with field PeerIP = 'oops' (Reason: failed to validate Field: PeerIP because of Tag: ip )
command terminated with exit code 1
```
Once this is merged, I'll cherry-pick into release-v3.10
```release-note
None required
```

Fix erroneous "Partial success" output

---

calicoctl/commands/node/diags.go

Autoremove `calicoctl node diags` "`ipset list`" container, which is currently hanging around as cruft after collecting a diag.
```release-note
None required
```

node diags: auto remove ipset list container

---

calicoctl/commands/node/diags.go

busybox netstat isn't as full featured as the net-tools source and fails to dump on these distros capable of running Kubernetes.
Currently busybox (compile-time define) supports:
```"\n	-r	Routing table"
"\n	-a	All sockets"
"\n	-l	Listening sockets"
"\n		Else: connected sockets"
"\n	-t	TCP sockets"
"\n	-u	UDP sockets"
"\n	-w	Raw sockets"
"\n	-x	Unix sockets"
"\n		Else: all socket types"
"\n	-e	Other/more information"
"\n	-n	Don't resolve names"
IF_FEATURE_NETSTAT_WIDE(
"\n	-W	Wide display"
)
IF_FEATURE_NETSTAT_PRG(
"\n	-p	Show PID/program name for sockets"
)
```
```release-note
None required
```

node diags: use shorthand for netstat

---

Makefile

similar to the PR i just issues in kube-controllers - `clean` needs to wipe the pkg-cache

Fix clean step in makefile

---

Makefile

Binaries being built with `build-all` are all ELF amd64 binaries:
```
user@ubuntu:~/go/src/github.com/projectcalico/calicoctl/bin$ file *
calicoctl-darwin-amd64:      ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=T3nSzwyun3ZO3NrIgiNC/qpbBPYeZAdbUJ8zwknfr/6L-QOdSFg-AzsZO7DoFT/EBvUJHJ_Fudra53kNuvL, stripped
calicoctl-linux-amd64:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=T3nSzwyun3ZO3NrIgiNC/qpbBPYeZAdbUJ8zwknfr/6L-QOdSFg-AzsZO7DoFT/EBvUJHJ_Fudra53kNuvL, stripped
calicoctl-linux-arm64:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=T3nSzwyun3ZO3NrIgiNC/qpbBPYeZAdbUJ8zwknfr/6L-QOdSFg-AzsZO7DoFT/EBvUJHJ_Fudra53kNuvL, stripped
calicoctl-linux-ppc64le:     ELF 64-bit LSB …
```

Fix building of binaries

---

calicoctl/commands/node/checksystem.go

There were some missing Kernel dependencies in the list of required modules.
Partly fixes: https://github.com/projectcalico/calicoctl/issues/1444
`ipip` kernel module is still missing, but it is only needed on case of `Calico` networking.
```release-note
More precise Kernel module dependency checking in calicoctl checksystem
```

Extend Kernel dependecies checker

---

calicoctl/commands/node/run.go

This is a new feature witch was asked at https://github.com/projectcalico/calicoctl/issues/1698.
With the newly introduced `--felix-config` flag users are  able to attach custom Felix configuration to the `calico-node` container during `calicoctl node run` command.
```release-note
New flag `--felix-config` to attach custom Felix configuration to the calico-node container via `calicoctl node run`
```

Add ability to attach Felix config to the container during node run

---

Dockerfile.amd64
Makefile

```release-note
The calicoctl image is now using registry.access.redhat.com/ubi8/ubi-minimal:8.1 instead of Alpine for the base image.
```

Operator: Update calicoctl to ubi as base image

---

Makefile

Maybe just me (but I doubt it), I always forget how `nosetest` wants a specific test to run, versus `pytest`.
```release-note
None required
```

add comment for using ST_TO_RUN variable

---

Makefile

When running `make gen-crds` the first time, files are copied into `calicoctl/config/crd/...`
However, when running `make gen-crds` a second time without deleting the `config` directory, files are copied into `calicoctl/config/config/crd/...`.  This means that any updates to libcalico-go will not be reflected in `crds.go`.  As a case in point, the current release is missing some updates, see PR #2151.
Also note that the config directory is not deleted when `make clean` is run, that may want to be addressed as well.
```release-note
None required
```

Fix import from libcalico-go

---

Dockerfile.amd64
Makefile
calicoctl-wait/calicoctl-wait.go

Build scratch based Image, with only statically built applications[calicoctl & calicoctl-wait]
1) Built small application to wait for in an indefinite loop.

Fix CVEs, use scratch based Image

---

calicoctl/calicoctl.go
calicoctl/commands/apply.go
calicoctl/commands/common/resources.go
calicoctl/commands/create.go
calicoctl/commands/datastore.go
calicoctl/commands/datastore/migrate.go
calicoctl/commands/delete.go
calicoctl/commands/file/file_suite_test.go
calicoctl/commands/file/iter.go
calicoctl/commands/file/iter_test.go
calicoctl/commands/get.go
calicoctl/commands/ipam/release.go
calicoctl/commands/label.go
calicoctl/commands/node/node_suite_test.go
calicoctl/commands/node/run.go
calicoctl/commands/node_linux.go
calicoctl/commands/patch.go
calicoctl/commands/replace.go
calicoctl/commands/version.go
calicoctl/resourcemgr/resourcemgr.go
calicoctl/resourcemgr/resourcemgr_test.go

Added the ability to specify manifests by directory.
If the file is a directory, calicoctl will search for .yaml, .yml and .json files in the immediate directory, and optionally recursively search sub directories.  An additional option is also added to allow calicoctl to run without error if the specific file or directory are empty (note that if --filename points to a non-existent 
Could benefit from some STs I think.  We have UTs testing the actual file loading behavior.  Not planning to add STs for 3.16 though.
```release-note
Various commands using file input now support specifying a directory to support actions on multiple manifests, these commands also include optional recursive searches for .yaml, .yml and .json files, and additional options to disable failing if the files or …
```

Add ability to specify directory as filename parameter

---

calicoctl/commands/datastore/migrate/import.go

Cherry-pick of https://github.com/projectcalico/calicoctl/pull/2166. 
Fix a bug in setting the default K8s client QPS. The default is supposed to be 50, but the code mistakenly changes any other configured value to the intended default of 50 and sets the default to 5.
```release-note
Fixes a bug that prevented the K8s client QPS from being configured correctly.
```

Fix the default value of the K8s client QPS

---

calicoctl/commands/datastore/migrate/export.go

Adds the KubeControllersConfiguration resource to the datastore migration.
Cherry-pick of https://github.com/projectcalico/calicoctl/pull/2173
```release-note
Datastore migration commands migrate KubeControllersConfiguration resources.
```

Add KubeControllersConfiguration to the datastore migration

---

calicoctl/commands/datastore/migrate/export.go
calicoctl/commands/datastore/migrate/migrateipam.go

Fixes issues where the etcd node names did not match the Kubernetes datastore node names. This migrates all of the relevant host information in IPAM to the correct Kubernetes datastore node name. This inserts the new Kubernetes datastore node names into the following IPAM fields:
- IPAM block allocation attributes
- IPAM block block affinity field
- IPAM block affinity host field
- IPAM block handle ID for `ipip-tunnel-addr` handles
- IPAM handle ID for `ipip-tunnel-addr` handles
This also fixes a similar issue where node names were not migrated properly for per-node FelixConfigurations.
```release-note
Fix a bug with mismatched node names when migrating IPAM data from etcd to Kubernetes datastores.
```

Fix datastore migration to properly assign Kubernetes nodenames in the migrated IPAM data

---

calicoctl/commands/datastore/migrate/export.go
calicoctl/commands/datastore/migrate/migrateipam.go

Cherry-pick of https://github.com/projectcalico/calicoctl/pull/2186
```release-note
Fix a bug with mismatched node names when migrating IPAM data from etcd to Kubernetes datastores.
```

Migrate ipam nodename 3.16

---

calicoctl/commands/datastore/migrate/export.go
calicoctl/commands/datastore/migrate/migrateipam.go

Cherry-pick of https://github.com/projectcalico/calicoctl/pull/2186
```release-note
Fix a bug with mismatched node names when migrating IPAM data from etcd to Kubernetes datastores.
```

Migrate ipam nodename 3.15

---

calicoctl/commands/datastore/migrate/export.go
calicoctl/commands/datastore/migrate/export_test.go
calicoctl/commands/datastore/migrate/migrate_suite_test.go
calicoctl/commands/datastore/migrate/migrateipam_test.go
tests/st/calicoctl/test_migrate.py
tests/st/utils/data.py

Follow up to https://github.com/projectcalico/calicoctl/pull/2186 to add some UTs
This PR also fixes the following bugs in the migration logic:
- BGP configurations were missing handling for per-node BGP configuration migrations in the case where the etcd node name differs from the Kubernetes datastore node name
- Long running clusters may store Felix configuration iptables fields in the Calico v1 API style. This converts those fields to match with the v3 validations.
```release-note
None required
```

Add IPAM migration unit tests and node handling for BGP configurations

---

calicoctl/commands/datastore/migrate/export.go
calicoctl/commands/datastore/migrate/export_test.go
calicoctl/commands/datastore/migrate/migrate_suite_test.go
calicoctl/commands/datastore/migrate/migrateipam_test.go
tests/st/calicoctl/test_migrate.py
tests/st/utils/data.py

Cherry-pick of https://github.com/projectcalico/calicoctl/pull/2199
```release-note
Add handling for migrating per-node BGP configurations and Calico v1 API Felix configuration fields
```

Add handling for v1 validations and node names in BGP configurations

---

calicoctl/calicoctl.go
calicoctl/commands/apply.go
calicoctl/commands/convert.go
calicoctl/commands/create.go
calicoctl/commands/datastore.go
calicoctl/commands/datastore/migrate.go
calicoctl/commands/datastore/migrate/export.go
calicoctl/commands/datastore/migrate/import.go
calicoctl/commands/datastore/migrate/lock.go
calicoctl/commands/datastore/migrate/unlock.go
calicoctl/commands/delete.go
calicoctl/commands/get.go
calicoctl/commands/ipam.go
calicoctl/commands/ipam/configure.go
calicoctl/commands/ipam/release.go
calicoctl/commands/ipam/show.go
calicoctl/commands/label.go
calicoctl/commands/node/checksystem.go
calicoctl/commands/node/diags.go
calicoctl/commands/node/run.go
calicoctl/commands/node/status.go
calicoctl/commands/node_linux.go
calicoctl/commands/patch.go
calicoctl/commands/replace.go
calicoctl/commands/version.go
calicoctl/util/docstring.go
tests/st/calicoctl/test_flags.py

When running as a kubectl plugin, we need to change the name of the
binary that appears in our docstrings to say `kubectl-calico` instead of
`calicoctl`.
```release-note
None required
```

Handle docstring binary name changes for kubectl plugin

---

Makefile

Cherry pick of #2230 on release-v3.17.
#2230: Fix make cd target to use correct tag for docker images

Automated cherry pick of #2230: Fix make cd target to use correct tag for docker images

---

Makefile

Cherry pick of #2235 on release-v3.17.
#2235: Fix make cd target to use correct tag for docker images

Automated cherry pick of #2235: Fix make cd target to use correct tag for docker images

---

calicoctl/commands/get.go
tests/fv/namespace_option_test.go

This PR changes `-a` option to `-A` in docs it also adds backward compatibility for `-a`.
```release-note
Introduces new `-A` option to calicoctl and deprecates the earlier `-a` flag, which will be removed in a subsequent release.
```
@caseydavenport

calicoctl get -A option support 

---

Makefile
test-data/kubectl-config-second.yaml
tests/fv/multi_context_test.go
tests/st/manifests/mock-node-second.yaml

- `make fv` now starts two apiservers (:8080, :8082) with two nodes (node4, node8 respectively)
- test scenario described in projectcalico/calico#4312
- e.g. `KUBECONFIG=~/.kube/config:~/.kube/kubeconfig_2 calicoctl version`
- fix LOCAL_BUILD: run `go mod vendor` after `go mod edit` so that the replace directive gets synched to `vendor/modules.txt` when using your local ../libcalico-go repo
```release-note
`calicoctl` now supports multiple kubeconfig files via KUBECONFIG env var, just as `kubectl` would:
Example  usage:
export KUBECONFIG=~/.kube/config:~/.kube/kubeconfig_2
calicoctl get node
calicoctl --context config2 get node
```

Add tests for projectcalico/libcalico-go#1361

---

Makefile

Ensures that all of the architectures that we support are built and uploaded on each release for the calicoctl utility. Fixes https://github.com/projectcalico/calicoctl/issues/2269
```release-note
None required
```

Build all architectures for calicoctl

---

Makefile
calicoctl/calicoctl.go
calicoctl/commands/version.go
tests/fv/helper/calico_version_helper.go
tests/fv/ipam_test.go
tests/fv/migrate_ipam_test.go
tests/fv/multi_context_test.go
tests/fv/namespace_option_test.go
tests/fv/utils/calicoctl.go
tests/st/calicoctl/test_flags.py
tests/st/manifests/crd.projectcalico.org_clusterinformations.yaml
tests/st/utils/utils.py

Make `calicoctl` verify if the cluster version is the same as the client version before running. Add `--allow-version-mismatch` command line arg to override this verification if needed. The verification is also bypassed if the command being run is `datastore migrate import`, since the ClusterInformation will not be set in this case.
Add go utility app calico_version_helper, which is used to set the calico version in the ClusterInformation for test environments.
Add st coverage for the feature, and make multiple changes to st and fv tests to set the version so that the tests continue performing correctly.
```release-note
Added calicoctl checks for version mismatch between itself and Calico in the cluster, with optional bypass argument '--allow-version-mismatch'.
```

Add client/cluster version mismatch verification

---

calicoctl/commands/version.go

This is needed as a follow-up to #2353 , as many of Tigera's internal tests do not create any ClusterInformation.

Skip version mismatch check when ClusterInformation does not exist

---

calicoctl/commands/version.go
tests/st/calicoctl/test_flags.py

Skip version mismatch check when CalicoVersion not specified in cluster

---

calicoctl/commands/version.go

Cherry pick of #2370 on release-v3.20.
#2370: Skip version mismatch check when ClusterInformation does

Automated cherry pick of #2370: Skip version mismatch check when ClusterInformation does

---

calicoctl/commands/version.go
tests/fv/multi_context_test.go

Cherry pick of #2387 on master.
#2387: Skip version mismatch check for commands with no API

Automated cherry pick of #2387: Skip version mismatch check for commands with no API

---

Makefile
calicoctl/calicoctl.go
calicoctl/commands/apply.go
calicoctl/commands/common/resources.go
calicoctl/commands/common/version_mismatch.go
calicoctl/commands/convert.go
calicoctl/commands/create.go
calicoctl/commands/datastore/migrate/export.go
calicoctl/commands/datastore/migrate/import.go
calicoctl/commands/datastore/migrate/lock.go
calicoctl/commands/datastore/migrate/unlock.go
calicoctl/commands/delete.go
calicoctl/commands/get.go
calicoctl/commands/ipam/check.go
calicoctl/commands/ipam/configure.go
calicoctl/commands/ipam/release.go
calicoctl/commands/ipam/show.go
calicoctl/commands/label.go
calicoctl/commands/node/checksystem.go
calicoctl/commands/node/diags.go
calicoctl/commands/node/run.go
calicoctl/commands/node/status.go
calicoctl/commands/patch.go
calicoctl/commands/replace.go
calicoctl/commands/version.go
tests/st/calicoctl/test_flags.py

Refactor version mismatch checking to run after argument parsing in the
applicable commands, dismissing the need for its own fragile argument parsing.
Add --allow-version-mismatch arg to every command (no-op when not applicable).
Adjust version mismatch st test accordingly.
```release-note
Fixed usage message output when invalid arguments are passed to calicoctl.
```

 Refactor version mismatch checking to not need argument parsing

---

Makefile

Cherry pick of #2395 on release-v3.20.
#2395: Change release repo to docker.io, add RELEASE and CONFIRM env

Automated cherry pick of #2395: Change release repo to docker.io, add RELEASE and CONFIRM env

---

Dockerfile.arm64
Dockerfile.armv7
Dockerfile.ppc64le
Dockerfile.s390x

Updating apk-tools in order to mitigate CVE-2021-36159
Fixes #2384
Signed-off by: Dave Hay <david_hay@uk.ibm.com>
For the `calicoctl` images that are based upon Alpine Linux, there's a requirement to update
`apk-tools` in order to mitigate [CVE-2021-36159](https://snyk.io/vuln/SNYK-ALPINE313-APKTOOLS-1533754)
The issue was identified, in an image built upon `s390x` via IBM Container Registry's Vulnerability Advisor tool.
I've manually built the `s390x` image, having previously built `calico/go-build`. I've also built `calicoctl` along with
the other Calico Node images, via our own Jenkins pipeline, again on/for `s390x`.
Having built `calicoctl` on `s390x`, I've deployed Calico Node to a K8s `1.21` cluster on the same platform, with
no apparent issues.
This PR affects four `calicoctl` …

Updating apk-tools in Alpine-based images

---

Dockerfile.arm64
Makefile

Update: Dockerfile.arm64 synced with `amd64`
Add: `TARGET_PLATFORM` in Makefile now forces docker to to tag the output with `arm64` architecture.
```release-note
None required
```

ARM64 dockerfile updates

---

Dockerfile.arm64
Dockerfile.armv7
Dockerfile.ppc64le
Dockerfile.s390x
Makefile

Fix: This PR updates all non `amd64` dockerfiles for a multiarch release.
```release-note
None required
```

Multiarch image adjustments

---

Makefile

In recent changes for the "make test" command, the flag -ti was added to the docker exec command. However, this caused that running the test in some pipelines (specifically Azure DevOps) failed, because it doesn't enable TTY input in the enviroment.
There is no reason to have both the flags -t and -i, so this PR removes the first, to fix that problem.
The PR was tested running "make test" command, that is the one modified

Remove TTY flag from docker exec

---

Dockerfile.amd64
Dockerfile.arm64

Update RHEL UBI image from 8.2 to 8.5.
Fixes: #2460 
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
```release-note
None required
```

Updated calicoctl RHEL UBI image to 8.5
